# 생산구조와 방식(Layout) {#sec-production-layout}

## 입지 조건

공장 입지란 생산을 위한 건물과 설비를 위치시킬 지역을 결정하는 것으로 예상투자수익률을 최대화할 수 있는 지역을 결정하게 된다. 일반적인 **공장입지 선정 요인**은 다음과 같다.

- 노동력과 노동환경(노동력 질, 임금 수준 등)
- 고객(시장)과의 접근성
- 원자재 접근성
- 수송 효율성 및 비용
- 공업용수의 양과 질
- 제품에 적합한 기후조건
- 토지가격
- 정부 규제(세금, 지원금 등)

글로벌 생산전략에 따라 **해외 생산 거점 입지 조건**은 다음과 같다.

- 비용 우위
- 규모의 경제
- 현지 시장 접근성
- 다양화와 위험 분산
- 정보 및 기술 교류

::: {.callout-note title="리쇼어링(Reshoring)"}
생산비와 인건비 절감 등을 이유로 해외로 생산시설을 옮긴 기업들이 다시 자국으로 돌아오는 현상을 말한다.
- 스마트팩토리(Smart Factory) 확산 - 기술적인 측면
- 보호무역주의 확산 - 정책적인 측면
- 해외 국가 인건비 상승
:::

::: {.callout-note title="오프쇼어링(Offshoring)"}
경영 활동의 일부를 국내 기업에 맡기는 아웃소싱의 범위가 해외의 저비용 이점을 활용하기 위해 해외로 확대된 것이다. 즉, 기존 사업 거점으로부터 타국에 사업을 이전하는 경제 행위를 가리킨다.
- 기존 사업 거점보다 저렴한 인건비, 세제 등
- 자국에 충분하지 않은 전문가 확보
::: 

### 입지 선정 기법

입지 선정 방법에는 양적인 요인과 질적인 요인으로 구분할 수 있다.

**앙적 요인**에 의한 선정 방법은 다음과 같다.

- 총비용비교법
- 입지손익분기점분석법
- 선형계획법
- 수송법

**질적 요인**에 의한 선정 방법은 다음과 같다.

- 단순서열법
- 점수법(요인평정법)

양적 요인과 질절 요인을 **절충**한 방법은 다음과 같다.

- Brown-Gibson 모형

## 설비 배치

설비 배치는 설비 내에서 경제적 활동을 위해 물리적으로 설비를 배치하는 의사결정이다. 설비 배치 대상은 공간을 필요로 하는 모든 자원(작업자, 기계, 작업장, 부서, 통로, 창고 등)이 된다.

### 위치고정형 배치

**프로젝트 배치**라고도 하며 제품이 매우 크고 복잡한 경우 제품이나 공사 구조물을 한 장소에 고정하고 원자재, 기계설비, 작업자 등을 제품 중심으로 옮겨 가면서 생상하는 형태이다.

### 공정별 배치

동일한 기능을 자는 설비를 집단으로 배치하는 형태이다. **기능별 배치**라고도 하며 주로 가공 공정에 이용되며 `다품종 소량생산`  시스템에 적합하다. 부품이나 구성품을 표준화 하기 어렵고 범용설비를 이용하여 제품을 생산한다.

### 제품별 배치

제품이나 서비스를 생산하기 위한 작업 절차와 동일하게 설비를 배치하는 형태이다. 컨베이어와 같은 운반장치가 필요하며 특정 제품을 생산하기 위한 전용설비를 이용한다. 대표적으로 자동차, 전자제품 등의 **조립생산공정**이 이에 해당하며 생산능률은 높으나 설비투자비용이 커며 소요가 감소하게 되면 단위당 제조 원가가 상승하게 된다.

### 그룹별 배치

자재 운반, 대기 시간을 줄이는 한편 다양한 품목을 생산할 수 있도록 고안된 설비 배치 형태로 공정별 배치와 제품별 배치의 특징을 모두 갖는다. 즉, 생산공정 또는 제품 특성에 따라 생산 품목을 몇 개 그룹으로 나누어 각 **그룹별**로 **생산설비**를 배치하는 형태이다. 그룹테크놀로지(GT)의 `셀형 배치`와 JIT 생산 시스템의 `U자형 배치`가 대표적이다. 중품종 중량생산에 적합한 형태이다.

#### 셀형 배치

#### U자형 배치


