# 구매와 외주전략 {#sec-purchasing-outsourcing}

구매는 사업이나 단체가 자신의 목표 달성을 위해 재화나 용역을 얻으려고 시도하는 것이다.[^1-3.-구매와-외주전략-1] 즉, 생산과 판매 등 기업 활동에 필요한 물품을 매입하는 활동이다. 주요 대상은 원부재료, MRO 자재, 부품, 외주 가공품, 기계설비, 상품 등이며 기타 생산 및 판매와 관련된 활동을 지원하기 위한 용역도 포함한다.

[^1-3.-구매와-외주전략-1]: https://ko.wikipedia.org/wiki/구매

::: {.callout-warning title="구매와 조달"}
일반적으로 구매 이외에도 촉진, 공급자 품질, 운송/물류(T&L)를 포함하는 개념이다.

-   **구매**(purchasing) <br> Buying(공급업체 발주 \> 주문확인 \> 납품서 작성 \> 입고 처리 \> 송장 처리 및 대금 지급)
-   **조달**(procurement) <br> 구매 + 공급업체 선택 및 분석(소싱 활동) + 가격 및 지불 조건 설정 + 계약 및 협상\
:::

과거 구매관리가 생산활동 지원 기능에 초점을 맞췄다면 최근 전략적 구매를 중시함으로써 기업 이익 창출을 강조하고 있다.

+--------------------------+-----------------------------+
| 전통적 시각              | 현대적 시각                 |
+==========================+=============================+
| -   단기간 성과 중시     | -   장기간 전략적 구매 중시 |
|                          |                             |
| -   획득비용(가격) 중심  | -   총원가에 집중           |
|                          |                             |
| -   비용 관리 센터       | -   이익 관리 센터          |
|                          |                             |
| -   요청에 지원하는 업무 | -   사전 계획적인 업무      |
+--------------------------+-----------------------------+

## 구매관리

**구매관리**는 경영계획과 활동을 추진하기 위하여 구매조직 관리, 구매계획, 구매실행, 구매분석 등의 구매 기능에 대한 조정 및 통제 활동이다. 구매관리 목적은 다음과 같다.

> -   좋은 품질의 물품 구매 (right quality)
> -   적당량의 구매 (right quantity)
> -   적당한 시기에 구매 (right time)
> -   적절한 가격의 구매 (right price)
> -   적절한 구매처의 선정 (right vendor or supplier)

## 집중구매와 분산구매

기업이 여러 사업장을 가지고 있는 경우 본사에서 기업 전체의 구매를 통합하여 진행하는 것을 **집중구매**라 한다. 반면 각 사업장별로 스스로 구매하는 경우를 **분산구매**라 한다. 또한 본사와 사업장이 협력하여 품목에 따라 분리하여 구매하는 경우도 있다.

각 구매 유형에 따른 장담은 다음과 같다.

+------------------------------------------------------------------------+-----------------------------------------------------------------------------------+
| 집중구매                                                               | 분산구매                                                                          |
+========================================================================+===================================================================================+
| -   대량구매로 가격이나 거래조건을 유리하게 정할 수 있다.              | -   각 사업장별로 구매 자립성을 가지므로 구매수속이 간단하고 구매기간이 줄어든다. |
|                                                                        |                                                                                   |
| -   공통자재를 일괄구매하므로 단순화, 표준화가 쉽고 재고량이 감소된다. | -   긴급수요의 경우 유리하다.                                                     |
|                                                                        |                                                                                   |
| -   전문적인 구매지식과 구매기능을 효과적으로 활용할 수 있다.          | -   지역구매가 많으므로 수송비가 절감된다.                                        |
|                                                                        |                                                                                   |
| -   구매절차를 통일하기 용이하다.                                      | -   해당 지역과 호의적인 관계를 유지할 수 있다.                                   |
|                                                                        |                                                                                   |
| -   구매비용이 줄어 든다.                                              |                                                                                   |
|                                                                        |                                                                                   |
| -   구매가격 조사, 공급자 조사, 구매효과 측정 등이 수월해진다.         |                                                                                   |
+------------------------------------------------------------------------+-----------------------------------------------------------------------------------+

대량구매품목, 고가품목, 공통 또는 표준품목 등은 집중구매가, 지역성 품목, 소량구매품목 등은 분산구매가 유리할 수 있다.  


## 외주전략
