# 수요예측과 일정계획 {#sec-demand-forecasting}

## 수요예측

:::{.callout-tip title="기출" icon=false}
97-2-2, 97-4-6
:::

### 수요예측 기법

```{mermaid}
flowchart LR
subgraph s1["   "]
10["정성적 예측법<br>(질적 예측 기법)"]
11[직관을 이용한 예측]
12[시장 조사에 의한 예측]
13[유추에 의한 예측]
11 --- 111[데파이법]
11 --- 112[판매원 의견 종합법]
11 --- 113[경영자 판단법]
11 --- 114[위원회 홥의법, 패널 동의법]
12 --- 시장조사법
13 --- 131[라이프 사이클 유추법]
13 --- 132[자료 유추법]
10 --- 11 & 12 & 13
end

subgraph s2["   "]
20["정량적 예측법<br>(양적 예측 기법)"]
21[시계열 예측기법]
22[인과관계 예측기법]
21 --- 211[이동 평균법]
21 --- 212[지수 평활법]
21 --- 213[수학적 모형]
21 --- 214[Box-Jenkins]
21 --- 215[추세 분석법]
22 --- 221[회귀분석]
22 --- 222[계량경제모형]
22 --- 223[투입-산출 모형]
22 --- 224[시뮬레이션 모형]
22 --- 225[선도지표법]
20 --- 21 & 22
end

예측기법 --- 10 & 20
```

#### 델파이법

**델파이법**(Delphi)은 익명 전문가 집단으로부터 합의를 도출하는 과정이다. 통계적 모형을 개발하기 위한 과거 자료가 없거나 영영자가 경험이 없어서 판단 근거를 찾을 수 없을 때 사용한다. 장기 수요 예측이나 신제품 수요 예측에 사용할 수 있으며, 기술 예측에 있어 매우 효과적이다. 예측에 걸리는 시간이 상당히 길고 응답 내용에 책임감이 적으며, 설문지를 잘못 설계하면 잘못된 결론을 도출할 수도 있다. 새로운 제품 수요 변환점을 예측하는데 상당히 우수하다고 알려져 있다.

#### 시계열분해법

**시계열 분석**이란 시계열(연, 월, 주, 일 등 시간 간격)에 따라 제시된 과거 자료(수요량, 매출액 등)로부터 그 추세나 경향을 파악하여 장래 수요를 예측하는 것이다. 이 경우 과거 자료를 미래 예측 길잡이로 이용하는데 시간이 독립변수가 되며 수요량 또는 매출액은 종속변수가 된다. 따라서 시계열 분석 초점은 과거에 발생한 수요와 관련된 시계열성에 있다고 볼 수 있다. 분석 방법에 따라 단순이동평균법, 가중이동평균법, 지수평활법 등이 있다.

### 예측오차

예측오차가 발생하는 원인은 다음과 같다.

- 예측모형에 사용한 변수 처리를 적절하게 하지 못한 경우
    - 중요한 변수 생략
    - 예측모형이 처리할 수 없는 변수 변동이나 움직임(추세나 순환변동이 갑자기 발생)
    - 새로운 변수 발생(신규 경쟁자 등)으로 인해 모형이 부적절한 경우
- 이상 기후나 기타 자연적 현상, 일시적인 과부족이나 고장, 재난, 기타 사유로 인한 불규칙 변동이 발생한 경우
- 예측기법을 잘못 사용하였거나 결과를 잘못 해석한 경우
- 다른 모든 변동요인들로 설명되고 난 나머지 내재적인 우연변동

#### 오차지표 {#sec-forecast-error-index}

예측오차
: - $E_t = A_t - F_t$

누적예측오차(RSFE, running sum of forcasting errors / CFE, cumulative sum of forecast errors)
: - $RSFE(or \ CFE) = \sum{E_t}$

평균절대오차(MAD, mean absolute deviation
: - $MAE = \frac{\sum{|E_t|}}{n}$

평균제곱오차(MSE, mean squared error)
: - $MSE = \frac{\sum{|(E_t)^2|}}{n-1}$

평균절대백분율오차(MAPE, mean absolute percentage error)
: - MAPE = \frac{\sum{\frac{|E_t|}{A_t}}}{n} \times 100

추적지표(TS, tracking signal)
: $TS = \frac{RSFE}{MAD}$

#### 추적지표

**추적지표**(TS)는 예측기법이 실제수요변화를 정확히 예측하고 있는지를 나타내는 지표이다. 예측치가 실측치를 잘 따라가고 있으면 TS는 0에 가까운 값을 갖는다. 예측치가 실제치보다 낮은 경우 TS는 양수값을 갖게 되고 이는 과소예측을 의미한다. 반면 예측치가 실측치보다 높은 경우 TS는 음수값을 가지며 과과예측을 의미한다.

::: {.callout-important icon=false title="예제: 97-4-6}

실제수요와 예측치가 아래와 같을 때 CFE, MAD, TS를 계산하시오.

월|실제수요|예측치|누적예측오차|평균절대오차|추적지표
-|-|-|-|-|-
1|95|100|||
2|100|100|||
3|110|106|||
4|102|106|||
5|98|100|||
6|120|111|||

@sec-forecast-error-index 산식에 따라 계산하면 다음과 같다.

월|A|F|E<br>A-F|CFE<br>$\sum{E}$|MAD<br>$\frac{\sum{|E|}}{n}$|TS<br>$\frac{CFE}{MAD}$
-|-|-|-|-|-|-
1|95|100|-5|-5|5|-1
2|100|100|0|-5|2.5|-2
3|110|106|4|-1|3|-0.33
4|102|106|-4|-5|3.25|-1.54
5|98|100|-2|-7|3|-2.33
6|120|111|9|2|4|0.5
:::

## CRM

:::{.callout-tip title="기출" icon=false}
97-1-8
:::

**고객관계관리**(Customer Relationship Management)는 마케팅 각 단계에서 축적되는 고객 정보를 체계적으로 이용하여고객과 장기적인 관계를 형성하기 위한 제반 활동, 조직, 업무 프로세스 및 IT 인프라 총체이다.

### CRM 필요성

CRM 필요성은 다음과 같다.

고객 DB 적극 활용
: - 고객 서비스 프로세스 개선 및 고객 지원 강화

저극적인 고객 인지를 통한 고객 가치 활동 지원
: - 고객 로열티 증대

통합고객 DB 마케팅 실현
: - 효과적인 커뮤니케이션

다양한 고객 요구에 대한 적극적 대처
: - 경쟁사 대비 우위 확보

::: {.callout-note icon=false title="e-CRM"}

인터넷 상 CRM을 의미하며, 고객 웹사이트에서 이루어지는 활동을 웹 로그로 관리, 기록하여 고객 형태에 대한 정보를 분석하고 그에 맞추어 여러 가지 홍보, 이벤트, 캠페인 등 마켓팅 활동을 수행한다.
:::

### CRM 특징

CRM은 다음과 같은 특징이 있다.

- 구매 고객 전체보다 개별 고객 특성 중시 (고객별 차별 대응)
- 신규 고객 확보보다 기존 고객 유지 중시
- 단기적 성과보다 고객과 장기적 관계 및 가치 중시
- 매출보다 이익 중시
- 고객과 기업, 양측 모두 만족 추구

### CRM 전제 조건

프로세스 통합
: - 마켓팅, 판매, 고객 서비스 업무 영역을 통합하여 고객 접촉 단계에 상관없이 단일화된 메시지를 전달 할 수 있도록 구성되어야 함

정보 통합
: - 댜앙한 고객 정보(고객 프로파일 정보, 상품 및 서비스 가입 정보, 서비스 요청 및 처리 이력 정보, 접촉 이력 정보, 빌링 및 납부 정보 등)를 통합하여 다양한 형태로 제공할 수 있어야 함
- 데이터웨어 하우스, 데이터 마이닝 및 분석 도구와 전사적인 정보 공유 체제 확립

고객 관점(Channel) 통합
: - Call Center, 직접 방문 응대, 영업사원, 대리점, e-CRM 등 다양한 고객 접점에서 동일한 고객에 대해 동일한 메시지를 전달할 수 있어야함

내부 고객 관리
: - 내부 구성원이 고객과의 접범에 위치해 있으므로 구성원들 만족 여부가 고객 충성도에 많은 영향을 미침

외부 고객 관리
: - 우량 고객 선정 요소
    - 고객과 기업의 적합성, 고객 관계 지향 성향, 고객의 수익 기여도(현재 + 미래)
- CRM 고객 정보
    - 고객과 관계를 이해하는데 필요한 정보와 자료, 관계에 대한 기록으로 고객과의 관계를 개발, 변화 및 유지하는데 활용
    - 고객을 지속적으로 관찰/분석하는 과정(고객에 대한 360도 시각)

### CRM 기대 효과

업무영역| CRM 기대 효과
-|-
마케팅 기회 분석|- 수익및 고객 평생 가치(LTV) 증대
마케팅 기회 분석|- 신규 고객 유치 및 기존 고객 활성화
마케팅 기회 분석|- 고객 Life Cycle상 결정적 시점에 효과적 마케팅 활동
마케팅 기회 분석|- 평생 고객으로 가치를 창출할 수 있게 함
영업지원 활동 |- 시장에서의 경쟁력 있는 제품이 파악 및 신속한 대응 전략 수립
영업지원 활동 |- 시장에서 경쟁력 있는 제품 파악 및 신속한 대응 전략 수립
영업지원 활동 |- 수익성 높은 고객 분류와 Target Marketing
마케팅 관리 |- 시장 변화 및 고객 Needs에 맞는 상품 개발
마케팅 관리 |- 상품에 대한 시장 반응의 신속한 파악 및 보완
마케팅 관리 |- 고객 Need변화에 대한 신속한 파악 및 대응
고객 서비스 |- 고객 충성도(Loyalty), 유지율 및 고객 만족 증대
고객 서비스 |- 고객 행위에 대한 이해
고객 서비스 |- Cross-Selling과 Up-selling 기회 증대 및 활용
고객 채널 관리 |- 고객 Needs에 맞춘 최적 채널 제공
고객 채널 관리 |- 비용을 최소화할 수 있는 고객 유도
