# 수요예측과 일정계획 {#sec-demand-forecasting}

## CRM

#97-1-8

**고객관계관리**(Customer Relationship Management)는 마케팅 각 단계에서 축적되는 고객 정보를 체계적으로 이용하여고객과 장기적인 관계를 형성하기 위한 제반 활동, 조직, 업무 프로세스 및 IT 인프라 총체이다.

### CRM 필요성

CRM 필요성은 다음과 같다.

고객 DB 적극 활용
> - 고객 서비스 프로세스 개선 및 고객 지원 강화

저극적인 고객 인지를 통한 고객 가치 활동 지원
> - 고객 로열티 증대

통합고객 DB 마케팅 실현
> - 효과적인 커뮤니케이션

다양한 고객 요구에 대한 적극적 대처
> - 경쟁사 대비 우위 확보

::: {.callout-note icon = "false" title="e-CRM"}
인터넷 상 CRM을 의미하며, 고객 웹사이트에서 이루어지는 활동을 웹 로그로 관리, 기록하여 고객 형태에 대한 정보를 분석하고 그에 맞추어 여러 가지 홍보, 이벤트, 캠페인 등 마켓팅 활동을 수행한다.
:::

### CRM 특징

CRM은 다음과 같은 특징이 있다.

- 구매 고객 전체보다 개별 고객 특성 중시 (고객별 차별 대응)
- 신규 고객 확보보다 기존 고객 유지 중시
- 단기적 성과보다 고객과 장기적 관계 및 가치 중시
- 매출보다 이익 중시
- 고객과 기업, 양측 모두 만족 추구

### CRM 전제 조건

프로세스 통합
> - 마켓팅, 판매, 고객 서비스 업무 영역을 통합하여 고객 접촉 단계에 상관없이 단일화된 메시지를 전달 할 수 있도록 구성되어야 함

정보 통합
> - 댜앙한 고객 정보(고객 프로파일 정보, 상품 및 서비스 가입 정보, 서비스 요청 및 처리 이력 정보, 접촉 이력 정보, 빌링 및 납부 정보 등)를 통합하여 다양한 형태로 제공할 수 있어야 함
- 데이터웨어 하우스, 데이터 마이닝 및 분석 도구와 전사적인 정보 공유 체제 확립

고객 관점(Channel) 통합
> - Call Center, 직접 방문 응대, 영업사원, 대리점, e-CRM 등 다양한 고객 접점에서 동일한 고객에 대해 동일한 메시지를 전달할 수 있어야함

내부 고객 관리
> - 내부 구성원이 고객과의 접범에 위치해 있으므로 구성원들 만족 여부가 고객 충성도에 많은 영향을 미침

외부 고객 관리
> - 우량 고객 선정 요소
    - 고객과 기업의 적합성, 고객 관계 지향 성향, 고객의 수익 기여도(현재 + 미래)
- CRM 고객 정보
    - 고객과 관계를 이해하는데 필요한 정보와 자료, 관계에 대한 기록으로 고객과의 관계를 개발, 변화 및 유지하는데 활용
    - 고객을 지속적으로 관찰/분석하는 과정(고객에 대한 360도 시각)

### CRM 기대 효과

업무영역| CRM 기대 효과
마케팅 기회 분석| - 수익및 고객 ㄹ평생 가치(LTV) 증대
| 신규 고객 유치 및 기존 고객 활성화
| 고객 Life Cycle상 결정적 시점에 효과적 마케팅 활동
| 평생 고객으로 가치를 창출할 수 있게 함
영업지원 활동 | - 시장에서의 경쟁력 있는 제품이 파악 및 신속한 대응 전략 수립
영업지원 활동| - 시장에서 경쟁력 있는 제품 파악 및 신속한 대응 전략 수립
| - 수익성 높은 고객 분류와 Target Marketing
마케팅 관리 | - 시장 변화 및 고객 Needs에 맞는 상품 개발
| - 상품에 대한 시장 반응의 신속한 파악 및 보완
| - 고객 Need변화에 대한 신속한 파악 및 대응
고객 서비스 | - 고객 충성도(Loyalty), 유지율 및 고객 만족 증대
| - 고객 행위에 대한 이해
| - Cross-Selling과 Up-selling 기회 증대 및 활용
고객 채널 관리 | - 고객 Needs에 ㅁ낮는 최적 채널 제공
| - 비용을 최소화할 수 있는 고객 유도
