# 물류관리(자재 및 재고관리) {#sec-logistics}

```{mermaid}
flowchart TB
자재관리 --- 1[구매관리] & 재고관리

1 --- 구매관리 & 외주관리 & 협력사관리
재고관리 --- 소요관리 & 저장관리 & 분배관리
```


## 재고관리 {#sec-invenory-management}

::: {.callout-tip title="기출"}
97-4-1
:::

**재고**란 조직에서 판매를 목적으로 보관중인 물품이나 자원으로, 많이 보유하면 빠르게 시장에 대응할 수 있고 재고주문비용이나 생산준비비용이 절감되지만, 재고 저장 비용이나 이자비용, 기회비용이 증가하는 문제점이 발생한다.

재고관리는 기업에서 재고 수준을 어떻게 유지할 것인지, 언제 보충할 것인지(주문시점/생산시점), 주문량을 얼마로 할 것인지(1회 주문량/생산량) 등을 결정하여 비용을 최소화하면서 고객 서비스 수준을 향상시키는 활동이다.

<br>

### 재고 종류

재고는 사용 목적에 따라 다음과 같이 분류된다.

안전재고
: - 완충재고, 불확실성을 대비하기 위해 평균적으로 소요되는 수량을 초과하여 보유하는 재고
- 변동성이 증가할수록 안전재고량 증가

예상재고
: - 예비재고, 장재 예상되는 수요에 대비하기 위하여 보유하는 재고

수송재고
: - 물품 대금은 지급하였으나 아직 입고되지 않은 상태, 즉 수송 중인 상태인 재고

주기재고
: - 경재적 주문량에 따라 발생하는 재고

<br>

### 재고 비용

재고 보유 시 다음과 같은 관련 비용이 발생한다.

재고유지비(inventory holding cost)
: - 재고를 보유함으로써 발생하는 비용으로, 자본비용, 저장비, 냉동비 등이 해당한다.

재고주문비(ordering cost)
: - 재고 보충이나 신규로 주문할 때 소요되는 비용으로, 재고입고 비용, 검사 비용 등이 해당한다(고정비 성격).

생산준비비
: - 재고를 자체적으로 제작할 경우 제조하기 위해 생산 라인을 준비하는데 소요되는 비용으로, 설비 및 장치 변경 비용, 유휴시간 비용 등이 해당한다(고정비 성격).

재고부족비(inventory shortage cost)
: - 재고가 부족하여 고객 주문에 대응하지 못할 때 발생하는 비용으로, 품절비용(stockout cost, 기회비용), 추후납품비용(제품인도 지연에 따른 벌과금, 생산독촉비용, 신용 상신, 신뢰도 하락 등)이 해당한다(주관적 평가).

<br>

### 재고 수준 적정성 평가

재고 수준 적정성 평가, 즉 성과 척도 방법은 다음과 같다.

평균총재고가치
: - 보유하고 있는 모든 재고 단가와 수량을 곱하여 재고 가치를 합한 것으로, 시계열 분석이나 경쟁사 대비 분석을 사용한다.

공급일수/공급주수
: - 현재 보유하고 있는 재고가 언제 매출이 되는지 계산한 값으로 재고재산 회전일수/회전주수이다(기업이 보유한 평균 재고량과 판매수준 비율).
- $공급일수 = \frac{평균총재고}{연간매출원가 (또는 연간매출액)} \times 기간$

재고자산회전율
: - 매출원가를 평균재고자산으로 나눈 것으로 재고잔산 회전속도를 나타낸다.
- $재고회전율 = \frac{매출비용}{평균재고 \times 단위당 원가}$

서비스 수준(%)
: - 고객수요를 충족시키는 목적이 엉ㄹ마나 잘 달성되었는지를 측정하는 척도

<br>

### 수요 종류

수요는 크게 독립수요와 종속수요로 구분된다.

독립수요
: - 완제품이나 예비부품/서비스부품에 대한 수요와 같이 다른 품목 수요에 의존하지 않고 기업 외부 시장 조건에 따라 결정되는 수요 형태
- 시계열 패턴을 가지고 지속적으로 발생, 수요 예측 필요
- 재고관리에 있어 **보충**(replenishment) 개념이 사용되고, 재고가 줄게 되면 수요 대비를 위해 재고를 보충

종속수요
: - 최종제품 생산에 소요되는 각종 원자재, 부분품, 구성품 등과 같이 모품목 수요에 따라 종속되어 있는 품목 수요 형태
- 독립수요품목 생산계획에 따라 결정
        - 자전거(독립수요) 생산 시, 핸들, 프레임, 바퀴, 타이어 등이 종속수요가 됨
- 재고관리에 있어 **소요**(requirement) 개념이 사용되고 원자재나 부분품이 쓰이는 상위단계 품목 또는 최종품목 필요에 따라 주문
- 종속수요품목 재고 관리 시스템, MRP 시스템

<br>

### 재고관리 모형

재고관리 모형은 수용 특성에 따라 **확정적 재고관리 모형**과 **확률적 재고관리 모형**으로 나눌 수 있다. 또한 특수한 경우 사용할 수 있는 **단일기간 재고관리 모형**이나 **ABC 재고관리 모형**도 있다.

```{mermaid}
flowchart LR

0[재고모형]
11[확정적 모형]
12[확률적 모형]
13[기타 재고 모형]
21[고정주문량 모형]
22[고정주문기간 모형]
23[조건부 재고 보충 시스템]
24[단일기간 재고관리 모형]
25[ABC 모형]
26["투빈시스템<br>원빈시스템<br>기본 재고 시스템"]
31[EOQ 모형]
32[EPQ 모형]

subgraph s4[특수한 경우]
23
24
25
26
end

subgraph s1[수요 및 조달 기간 특성]
11
12
13
end

subgraph s2[주문시기 및 주문량 결정 방법]
21
22
end

subgraph s3[고정주문량]
31
32
end

0 --> 11 & 12 & 13
11 & 12 --> 21 & 22
13 --> 23 & 24 & 25 & 26
21 --> 31 & 32
```

<br>

#### 확정적 재고관리 모형

**확정적 재고관리 모형**은 재고관련 비용, 수요율, 생산율이 확정적인 경우에 사용하는 관리 모형이다.

특징
: - 재고관련 비용, 수요율, 생산율이 확정적

가정
: - 수요는 미리 알려져 있고, 일정하며, 균일하게 발생한다.
- 조달기간은 알려져 있고 일정하다.
- 제품 구입단가는 일정하다.
- 주문비용 또는 준비비용은 고정비로서 일정하다.
- 주문량은 조달기간이 지나면 일시에 전량이 한번에 들어온다.
- 모든 수요는 재고부족 없이 충족된다.

주요 용어 설명
: - 기호 및 설명  

        기호|설명
        -|-
        TC | 연간 재고관련 총 비용
        D | 연간 수요량
        Q | 1회 주문량
        EOQ 또는 Q* | 경제적 주문량 (최적 주문량)
        C | 단위당 구입가격(생산인 경우 생산 비용)
        S | 1회 주문비용 또는 준비비용
        H | 연간 단위당 재고유지비용, 1단위를 1년간 재고로 유지하는데 소요되는 비용, 보통 단위당 가입가격의 몇 %로 산정, H = C x 몇 %
        d | 일일 평균 수요
        L | 조달  기간
        R | 재주문점
        N* | 연가 최적 주문 횟수
        T* | 연간 최적 주문 주기
        P | 연간생산율

<br>

##### 경제적 주문량 모형(EOQ)

주문량에 따른 특징은 다음과 같다.

주문량이 적을 경우 | 주문량이 많을 경우
-|-
평균재고 감소 | 평균재고 증가
재고 유지비용 감소 | 재고유지비용 감소
연간 주문횟수 증가 | 연간 주문 횟수 감소
연간 주문비용 증가 | 연간 주문비용 감소

이상적인 주문량, 즉 최적주문량은 주문비용과 재고유지비용이 적정한 수준에서 결정된 수량이다.

**경제적 주문량**(EOQ,economic order quantity) 모형이란 가장 단순한 형태를 갖는 재고 모형으로 연간 재고유지비용과 연간 주문비용의 합을 최소화하는 1회 주문량(EOQ 또는 Q*)을 구하는 것으로 이 때 주문량 크기를 경제적 로트 사이즈(ELS, economic lot size)라고도 한다.

!!! 그림 추가

항목 | 계산식
-|-
연간 재고관련 총 비용 TC<br>(연간 주문비용 + 연간 재고 유지비용) | $$ \frac{D}{Q}S + \frac{Q}{2}H = \sqrt{2DSH} $$
경제적 주문량(Q*) | $$ \sqrt\frac{2DS}{H} $$ 
일일평균수요(d) | $$ \frac{D}{연간영업일수} $$ 
재주문점(R) | $$ dL$$ 
연간 최적주문횟수(N*) | $$ \frac{D}{Q^*} = \sqrt{\frac{DH}{2S}} $$
연간 최적주문주기(T*) | $$ \frac{1}{N^*} = \sqrt{\frac{2S}{DH}}$$ 

<br>

##### 경제적 생산량 모형(EPQ)

**경제적 생산량**(EPQ, economic production quantity) 모형이란 생산이 진행되는 동안 생산된 제품이 재고에 더해짐과 동시에 소비가 일어나서 재고가 감소하는 경우 최적 1회 생산량을 결정하는 모형이다. 자체 생산, 조달하는 물품의 총 재고비용이 최소가 되는 1회당 경제적 생산량으로 기본 EOQ와 유사하지만 주문비용 대신 작업 준비 비용을 대체하여 사용하다는 점이 다르다.

EPQ 모델 가정
: - 생산이 시작되고 뒤이어 수요가 이루어지며 수요량은 생산량보다 작다.
- 생산은 일정 기간 동안 점진적으로 쌓이고 어느 정도 재고 수준에 이르면 생산을 중단한다.
- 생산이 중단되면 쌓였던 재고량은 일정량씩 소요되어 바닥 난다.
- 재고가모두 없어지면 즉시 생산 작업이 되풀이 된다.
- 재고 유지비는 생산량 크기에 정비례하여 발생한다.
- 생산단가는 생산량 크리와 관계없이 일정하다.

항목 | 계산식
-|-
생산기간(t) | $$\frac{Q}{P}$$
평균재고수준 | $$\frac{(P-D)Q}{2P}$$
연간재고유지비용 | $$\frac{(P-D)QH}{2P} = \frac{DS}{Q}$$
연간생산준비비용 | $$\frac{D}{Q}S$$
연간총비용(TC) | $$\frac{DS}{Q} + \frac{(P-D)QH}{2P}$$
경제적 생산량(EPQ) | $$\sqrt{\frac{2DS}{H}(\frac{P}{P-D})}$$

<br>

#### 확률적 재고모형

<br>

#### 조건부 재고 보충 시스템
조건부 재고 보충 시스템은 **절충 시스템**, **min-max 시스템** 등으로 불리며 고정주문량 모형과 고정주문기간 모형을 혼합해서 사용하는 방식이다.

<br>

#### ABC 모형

<br>

#### 투빈 시스템

<br>

## 유닛로드

:::{.callout-tip icon=false title="기출"}
100-4-4
:::

**유닛로드** 시스템(unit load system)이란 낱개단위 화물을 일정 규모의 단위화물로 만들어 일관된 수송/보관/하역 체계를 구축하여 합리적 물류 활동을 가능하게 하는 시스템으로, 파텟트(pallet), 컨테이너(container) 이용을 통한 수송 및 보관, 지게차에 의한 상하차 등을 예로 들 수 있다.

유닛로드 시스템 전제조건
: - 파렛트 표준화
- 포장단위 치수 표준화
- 수송장비 적재함 규격 표준화
- 운반 하역장비 표준화
- 창고, 보관시설 표준화
- 거래단위 표준화

유닛로드 시스템 장단점은 다음과 같다.

장점
: - 제품 파손 및 분실 방지
- 포장 간소화 및 포장비 절감
- 시스템화 용이
- 운송수단 효율성 제고
- 적재효율성 제고
- 인건비 절감
- 하역 효율 항상

단점
: - 장비 확보 필요
- 검품/이송 등 부수작업 발생
- 넓은 공간 확보 필요
- 고정시설 투자 필요
- 자재관리 시간 및 비용 추가

## 활성지수

:::{.callout-tip icon=false title="기출"}
103-1-3
:::

활성지수는 물건이 놓여 있는 상태로부터 이동에 시키기 위한 수고 정도(0~4)를 합계치인 4에서 뺀 값을 나타낸다. 즉, 활동지수가 높을수록 물건을 쉽게 이동할 수 있다는 의미이다.

활성지수 0
: - 바닥에 벌크 상태로 놓여 있을 때

활성지수 1
: - 용기에 넣거나 다발로 묶었을 때

활성지수 2
: - 팔레트, 스키트 등 받침을 사용했을 때

활성지수 3
: - 차량을 사용했을 때

활성지수 4
: - 컨베이어, 슈트 등을 사용했을 때
