# 생산계획수립 {#sec-production-planning}

## 생산능력 결정 전략 {#sec-productibility-strategy}

:::{.callout-tip icon=false title="기출"}
100-2-5
:::

생산시스템을 신설, 확장 시 생산능력을 결정하게 된다. 생산능력 결정 시 여유 능력 크기는 얼마로 할 것인가? 증설 시기는 언제로, 규모는 얼마로 할 것인가 등을 검토해야 한다.

생산능력 결정 요인은 크게 영향요인과 제약요인이 있다. 

영향요인
: - 시설요인(Pysical Factors), 공정 및 시설 입지, 공정설계 및 건물, 시설 및 설비 배치, 공장 환경, 운반시설 등
- 제품 및 서비스 요인(Proudct/Service Factors), 제품 및 서비스 설계, 단순화/표준화, 품목 최적 구성, 품질 요인, 원자재 구성 및 소요량 등
- 공정요인(Process Factors), 공정 ㅁ치 설비 생산량, 공정 및 설비 븡력
- 인저요인(Human Factors), 직무설계, 직무내용, 작업방법, 작업강도, 작업환경, 교육 및 경험, 동기부여, 보상 등
- 시스템 가동 상의 요인, 설비보전, 일정관리,품질관리 등 생산 시스템 관리 기준

제약요인
: - 시장
- 원자재
- 자금
- 노동력

기간별 생산능력 계획시 고려사항은 다음과 같다.

단기 생산능력 계획
: - 가격조정
- 정비 계획 조정
- 생산성 향상 방안
- 납기 연기
- 재고 수준 변화
- 종업원 교육
- 고용수준 가동률 변동
- 고융수준 변동

장기 생산능력 계획
: - **공격전략** - 장기적인 시장 확보 및 시장점유율 향상, 여유능력으로 불확실한 수요에 대한 대응이 가능하며 납기지연이 줄어 들어 고객에게 신뢰감을 주어 안정적인 구매자 확보 가능
- **방어전략** - 생산능력  효율 향상으로 투자에대한 수익률 향상, 장기적으로 시장점유율을 잠식당할 위험 존재
- **평균전략** - 약간의 초과 능력과 수요 부족을 허용하는 생산계획이 바람직

장기적으로이익을 최대화하는 관점에서 장기 생산능력 의사결정에 대한 체게적인 접근은 다음과 같다.

대규모 접근법
: - 규모의 경제로 연간 생산 소비를 감소시킬 수 있으나 고정비 부담이 크고 수요 변동이나 제품 믹스 시 유여넛이 떨어진다

점진적 접근법
: - 단계적으로 작은 단위로 확장하는 것으로 소요자금이 적게 들며 유연성이 큼
        - 필요 생산용량 추정
        - 예측된 수요와 현재 용량 간 차이 계산
        - 대안 개발
        - 대안 평가
            - 정성적 평가 - 수요, 경쟁자 반응, 기술 변화, 비용 추정치 등 불확실성
            - 정량적 평가 - 현금 흐름

생산시설에 대한 의사결정 절차
: - 시설 규모 결정 - 최적 규모 설정
- 입지 설정 - 관련된 모든 비용 합이 최소가 되도록 결정

### 생산능력 전략 사전 검토 사항

경영자는 생산능력을 결정하기 앞서 생산능력 전략 차원에서 **여유능력 크기**와 **확장 시기 및 규모**를 검토해야 한다.

여유능력 결정(Sizing Capacity Cushinon)
: - **여유능력**(capacity cushion)은 기대를 초과하는 잉여 능력으로 최적 여유 능력은 산업 분야별 차이가 있다.
- 충분한 여유능력은 수요가 증가하는 추세에 있거나 불확실한 경우 또는 안정적인 공급을 요하는 경우에 필요하다.
- 지나친 여유능력은 과대한 유지비용으로 수익률을 저하시킬 수 있다.


확장 시기와 규모(Timing and sizing Expansion)
: - *사전 확장 전략**(proactive capacity strategy)
        - 재고 부족 손실 > 잉어 능력 비용 x 2배
        - 여유 내지 초과 능력을 유지하는 비용보다 재고 부족(품질) 손실이 상당히 높을 때, 고성장 산업에서 보통 채택되는 확장주의 전략(Expansionist Strategy)
        - 수요에 앞서가는 사전 확장 전략은 규모의 경제와 학습효과가 강한 경우 생산능력 크기가 상대적으로 크므로 능력 부족으로 인한 판매기획 상실을 줄일 수 있다.
        - 이들 산업에서 여유 능력을 갖고 있는 기업은 능력이 한정된 경쟁업체들로부터 시장점유율을 잠재적으로 확보할 수 있다.
- **사후 증설 전략**(Reactive Capacity Strategy)
        - 재고 부족 손실 < 잉여 능력 비용 x 0.67
        - 여유 능력 유지 비용이 품절 비용ㅇ를 초과할 때 채택되는 전략으로 수요를 관망하다가 증설하는 보수 전략
        - 능력 이용률은 높지만 시장 위치가 불안한 기업에서 채택
        - 수요를 관망(wait and see)하다가 증설하는 보수적인 증설 전략으로 관망 기간 중 어느 정도 부족 능력은 감수해야 한다.
        - 사후 증설 전략은 투자 위험을 줄일 수 있으나 수요에 뒤처지며 생산능력 부족을 메우기 위한 잔업, 임시고용, 하청 등 단기적인 대안에 의존하는 경우가 많다.
        - 이 전략은 능력 이용률 높지만 시장 위치가 불안한 기업에서 흔히 채택된다.
        - 경쟁업체에서 동시에 생산능력을 증대시키게 되어 많은 잉여 능력을 유발하여 경쟁은 더울 치열해진다.

기대 가치 유지 전략(Expected Capacity Strategy)
: - 기대 수요에 근접한 능력 유지(사전/사후 절충형)
- 사전 확장, 사후 증설 전략을 절충한 접근 방식으로 가급적 기대 수요에 근접한 능력을 유지하려는 전략
- 이 경우 충분한 능력을 갖지 못한 가능성만큼(잉여) 능력을 가질 가능성을 만들어 손실을 상쇄하는 전략이다.

### 전략 대안 평가

간편한 전략평가 방법으로 단위당 품절 손실과 함게 잉여 능력 비용을 추정하는 능력비율(Capacity Ratio, CR)을 산정하여 판단할 수 있다.

질적요인
: - 시설투자 자금 동원 능력
- 주변 생활 환경
- 지역 기술 및 교육수준
- 고객과 근접성으로 인한 수요 창출

비용요인
: - 지역별로 차이가 날 수 있는 인건비
- 세금 및 보험료
- 전기, 가스, 수도 등 공공사업 비용
- 수송 비용
- 토지, 건물 및 설비비용

용량 계획 평가 도구
: - 수요 불확실성과 변동을 보다 공식적으로 분석 가능한 도구
        - 대기행렬 모형 - 무작위적이고 독립적인 고객들의 행동을 도착 시간과 서비스 요구 측면에서 검토
        - 시뮬레이션 - 복잡한 대기 열 문제를 시뮬레이션을 통해 프로세스 병목과 여유 용량을 찾아냄
        - 의사결정 나무 - 수요가 불확실하고 이어지는 의사결정이 포함될 경우 다양한 설비확장안 평가 시 사용

생산능력 결정 기법
: - 생산능력 결정 기법으로 일반적인 방법은 선형계획법과 확률계획법이다.
        - 선형계획법은 장래 제품 수요와 경쟁기업 공급능력을 비교적 정확하게 예측할 수 있는 확실한 상황에서 유용
        - 확률계획법은 장기적 제품 수요를 추정하지만 미래 제품 수요와 공쟁기업 공급 능력을 상대적으로 정확하게 예측하기 어려운 경우 유용, 대표적으로 대기행렬, 시뮬레이션, Decision Tree Approach 등
- 생산능력은 조직 전체에 걸쳐 전략 및 프로세스와 밀접하게 연계되어야 함
- 입지 문제, 자원 유연성, 재고 같은 분야의 의사결정을 할 때 여유 용량에 미치는 효과를 고려함

### 능력비율(CR, capacity ratio)

CR은 단위당 품절 손실과 함게 잉여 능력을 추정하여 능력 비율을 산정, 평가하는 지표이다.

$$
능력비율(CR) = \frac{(C_s - C_e)}{C_s}
$$
$$
여기서 \ C_s는 \ 단위당 \ 품절 \ 손신, C_e는 \ 단위당 \ 잉영능력 \ 유지 \ 비용
$$

CR에 따른 생산능력 전략
: - CR <= 0.5
        - 품절 비용 < 0.67 x 잉여 능력 유지 비용
        - 사후 증설 전략
- -0.5 < CR < 0.5
        - 기대 가치 유지 전략
- CR >= 0.5
        - 품절비용 > 2 x 잉여 능력 비용
        - 사전 확장 전략

## MRP

:::{.callout-tip title="기출" icon=false}
103-1-9
:::


### MRP 3대 필수요소

MRP 3대 필수요소는 기준일정계획(MPS), 자재명세서(BOM) 그리고 재고기록파일(IRF)이다.

MPS
: - MPS 참고

BOM
: - @sec-bom 참고

IRF
: - 재고관리에 기본이 되는 자재별 수불현황과 현재고, 조달 기간 명시

### BOM {#sec-bom}

**BOM**(bill of material)은 상위 품목과 부품 간 관계와 사용량, 단위 등을 표시한 리스트로 도표 또는 그림을 의미한다. 상위 품목이란 하나 이상 부품으로 제조되는 품목이며, 부품은 상위 품목으로 전환되기 위해 적어도 하나 이상 공정을 거쳐야 하는 품목이다. 즉 BOM은 제품을 구성하는데 필요한 원자재, 부품 또는 부분조립품 소용량과 조립순서, 가공순서를 나타낸다. MRP 시스템을 운영하는데 기본적으로 사용되는 입력자료이다.

:::{.callout-note title="BOP" icon=false}
**BOP**(bill of process)는 제품을 구성하고 있는 부품이 어떤 공정에서 언제 생산을 해야 할지가 분단위로 이루어진 것으로 BOM 부품구성정보와 부품 정보에서 개당 작업공수와 부품 가공공정 정보 조합이다. BOM에 각 부품 제작공정을 표시하여 부품과 공정 선후관계를 네트워크(network) 형태로 표현한다.
:::
