# 표준작업관리 {#sec-standard-work-management}

## 표준시간

표준시간(ST, standard time)이란 
- 표준 작업환경에서
- 표준작업방법으로
- 숙련된 작업자가
- 보통의 노력으로
- 성실하게 작업을 실시하는데
필요한 시간을 말한다.

표준시간은 정미작업시간(NT, normal time)과 여유시간(AT, allowance time)으로 구성된다.

정미(작업)시간은 레이팅(rating 또는 normalizing, 정상화)을 반영한다. 여기서 레이팅이란 관측대상 작업속도와 정상적인 속도를 비교, 판단하여 관측시간치를 수정하는 것이다. 레이팅은 시간분석자 자격요건 일환으로 여러가지가 개발되어 운용되고 있다.

$$
표준시간(ST) = 정미시간(NT) + 여유시간(AT) = 관측시간 \times(1+레이팅) + 여유시간
$$

### 레이팅

평준화(leveling)법 또는 Westing house법
: - $정미시간 = 관측시간 대표치 \times (1+평준화계수합)$
- 평준화 요소인 `숙련도`, `노력도`, `작업조건`, `일치성`에 대한 평준화 계수 계산한 후 정미시간에 반영한다.

:::{.callout-important icon=false title="평준화법을 이용한 작업시간 산출"}
관측시간 대표치가 0.5분이고, 평준화 등급이 아래와 같이 계산되었을 때 정미시간을 계산하시오.

```{r}
#| echo: false
#| tbl-colwidths: [25,25,25,25]
tb <- data.frame(
  stringsAsFactors = FALSE,
               숙련도 = c("B", "0.08"),
               노력도 = c("C", "0.02"),
              작업조건 = c("C", "0.02"),
               일치성 = c("C", "0.01")
      )
knitr::kable(tb)
```

----

$$
정미시간(NT) = 관측시간 대표치 \times (1 + 평준화계수합) = 0.5 \times (1 + 0.13) = 0.565
$$
:::

속도레이팅(speed rating)법 - 주관적 평가법
: - 속도레이팅을 수행도 평가법(performance rating)이라고도 하며, 이 방법은 작업환경과 작업조건, 그리고 작업바법이 일정하다면 수행도는 작업능력과 작업의욕에 따라 변화게 된다는 가정에 기초를 둠
- 작업 수행도 기준을 100%으로 한다면 변동요인(능력, 의욕 등)에 따라 수행도 평가치를 120%로 할 때 평가계수는 (120/100)을 사용하여 관측시간을 수정함
- $NT = 관측시간 대표치 \times \frac{평가치}{기준수행도}$

객관적 레이팅(objective rating)법
: - M.E. Mundel이 발표한 것으로 제1평가(작업속도)와 제2평가(작업 곤란성)를 고려하여 정미시간을 계산하는 방식
- $NT = P \times S \times O$
        - P는 속도평가 계수
        - S는 2차 조정계수(작업시간 증가분을 100분율로 표시)
        - O는 관측시간 평균치 또는 대표치

합성레이팅(synthetic rating)법
: - 작업을 요소작업으로 구분한 후 요소별 관측시간을 산출(O)
- 요소작업 중 임의 작업자 요소작업을 몇개 선정함
- 선정된 요소작업에 대해 PTS법으로 분석하여 시간치(F)를 계산
- 실제관측치(O)와 PTS에 의한 시간치(F) 간 비율 $P = \frac{F}{O}$이나 비율 평균치를 레이팅 계수로 구한 후 다른 요소작업에 적용

노력평가(effort rating)법
: - 동작속도 외에 작업 곤란성, 작업자 숙련도와 노력도, 작업조건 등을 고려하여 작업 페이스를 직접 레이팅 하는 방법

SAM 레이팅 필름
: - 시간연구자 레이팅 훈련용으로 널리 사용되는 SAM(society for advancement of management) 레이팅 필름에 의한 공정한 1일 작업량을 선정하는 방법

### 여유시간

여유시간은 작업에 있어서 불가피한 시간을 의미한다. 작업자 휴식 또는 작업 중 여러가지 원인으로 지연이 발생하기 때문에 표준시간 설정 시 적당한 여유를 주어야 하는데 이에 해당하는 시간이 여유시간이다.

```{mermaid}
flowchart LR

00["여유"]
01["일반여유"]
02["특수여유"]
03["장려여유"]
11["개인여유(용무여유)"]
12["피로여유"]
13["작업여유"]
14["관리여유(직장여유)"]
21["기계간섭여유"]
22["조여유"]
23["소로트여유"]
24["긴사이클여유"]

00 --- 01 & 02 & 03
01 --- 11 & 12 & 13 & 14
02 --- 21 & 22 & 23 & 24
```

일반여유
: - 어떤 작업에 대해서 공통적으로 감안해 주는 기본적인 여유
- 개인여유: 인적여유, 용우여유, 생리여유로서 일반적으로 2~5%(남자 5%, 여자 7%)
- 피로여유: 일반적으로 중노동 20~30%, 경노동 5~10%로 피로 발생은 작업강도, 환경, 육체적 근육노동, 정신적 건강에 기인함
- 작업여유: 3~5% 부여, 작업여유는 재료취급시간, 불량공구 연마 및 교환, 기계수리, 조정, 주유, 청소 등 불규칙적으로 발생되는 여유
- 관리여유: 3~5% 부여, 작업 중 발생하는 작업상 업무연락, 협의, 짧은 시간 작업 대기 등에 해당

특수여유
: - 작업 특수성이나 작업편성 등 특별한 사정으로 인하여 표준시간 개개 작업에 적용할 경우에 특별히 고려할 필요가 있는 여유
- 기계간섭여유: 1명 작업자가 2대 이상 기계를 조작할 경우 기계 간섭이 발생함으로써 생산량이 감소하는 것을 반영하기 위한 여유
- 조여유: 작업자가 조를 이루어 작업을 실시할 때 발생하는 작업지연 보상
- 소로트여유: 로트수가 작기 때문에 정상작업속도가 유지곤란한 경우 보상
- 긴사이클여유: 사이클이 길기 때문에 작업 변동이나 복잡성을 보상하기 위한 여유
- 기타 여유: 3~5% 부여

장려여유
: - 임금지급제도와 관계되는 정책적인 여유로 능률제도와 같은 장려제도 실시 시 할증급 비율을 표준시간에 포함시키기 위한 계수

### 여유율 계산

여유율은 외경법과 내경법으로 계산할 수 있다.

외경법
: - 정미시간에 대한 비율을 여유율로 사용함
- $여유율(A) = (여유시간/정미시간)\times100 = (AT/NT)\times100(\%)$

내경법
: - 실동시간에 대한 비율을 여유율로 사용함
- $여유율(A) = (여유시간/실동시간)\times100 = \frac{여유시간}{(정미시간+여유시간)}\times100 = \frac{AT}{NT+AT}\times100(\%)$

## 작업시간 산정

```{mermaid}
flowchart LR
00[작업시간 산정]
01[통계적 방법]
02[관측법]
03[합성법]

11[경험 견적법]
12[실적 자료법]

21[직접 관측법]
211["시간연구법(Stop watch)"]
212["작업표본 분석법(Work sampling)"]
22[간접 관측법]
221[미세동작 연구법]
222[동작궤적 분석법]

31["기정시간 표준법(PTS)"]
311["작업요소시간 표준법(Work factor)"]
312["방법시간 표준법(MTM)"] --- 혼다
32[표준시간 자료법] ---- D
313["MODAPTS"] --- D[도요다]
321["컴퓨터 시뮬레이션 기법(CAPES"]

00 --- 01 & 02 & 03

01 --- 11 & 12

02 --- 21 --- 211 & 212
02 --- 22 --- 221 & 222

03 --- 31 --- 311 & 312 & 313
03 --- 32 --- 321

```


### 시간연구법

19세기말 Frederick Winslow Taylor가 공식 도입한 방법으로 어떤 업무를 한 작업자가 여러번 수행하는 것을 관찰하여 표준시간을 정하는 방식이다.

절차
: 1. 연구대상 업무를 설정하고 그것을 수행할 작업자에게 알림
1. 관찰 횟수를 결정
1. 시간을 측정하고 그 작업자 성과를 평가
1. 표준시간을 계산

선정된 작업자가 작업시간을 늘리려고 불필요한 동작을 하는 경우가 많기 때문에 연구를 수행하는 분석 담당자는 대상 업무를 철저히 알고 있어야 하며, 표준시간을 정하기 이전에 그 업무가 효율적으로 수행되는지 확인할 필요가 있다. 측정횟수는 관측된 시간 변동성, 정확도 목표, 추정된 업무시간 신뢰도 수준 목표에 맞게 설정한다.

$$
측정횟수(n) = (\frac{zs}{a\bar{x}})^2
$$

여기서,  

- $z$ = 목표 신뢰도를 달성하기 위한 표준편차 수
- $s$ = 표본 표준편차
- $a$ = 정확도 목표
- $\bar{x}$ = 표본평균

:::{.callout-important icon=false title="시간연구법"}
평균시간 6.4분, 표준편차 2.1분, 신뢰도 목표 95%, 표본평균 ±10%일 때, 측정횟수를 계산하시오.

----

신뢰도 목표 95%에서 $z$ 값이 1.96이므로 아래와 같이 측정횟수를 계산할 수 있다.

$$
측정횟수(n) = (\frac{zs}{a\bar{x}})^2 = (\frac{1.96 \times 2.1}{0.1 \times 6.4})^2 = 41.36
$$

:::

### PTS

**PTS**(predetermined time standard)는 이미 작성된 작업요소들을 이용하여 표준시간을 계산하는 방식이다. 1940년대 말 Method Engineering Council이 개발한 방법시간측정(MTM, Methods-time measurement)을 주로 사용했다.

```{mermaid}
flowchart LR
MTA --- WF --- MTM --- BMT --- RWF --- MODAPTS
```

PTS 발전
: - 1942년 MTA(Motion time study)라는 명칭으로 처음 소개된 이래 다양한 기법이 연구됨
- MTA, Motion time Analysis 1924
- WF, Work factor 1938
- MTM, Method time measurement 1948
- BMT, Basic motion time study 1950
- RWF, Ready work factor
- MODAPTS, Modular arrangement of predetermined time standards 1966

장점|단점
-|-
- 간접 측정방법으로 작업자 불편 제거<br>
- 스톱워치 미사용으로 별도 레이팅 불필요<br>
- 생산 시작 전 사전 시간 산출 및 견적이 가능 <br>
- 시간 연구자가 각 동작을 세밀히 분석함으로 더 나은 작업 방법을 자동적으로 제안 가능 <br>
- 작업 방법에 대한 매우 자세한 기록이 남아 작업자 훈련과 작업 방법 변동 요인을 찾기가 용이 <br>
- 표준시간 산정을 위한 공수 감소, 표준자료 작성 용이 | 
- 회사 설정에 가장 적합한 PTS 시스템 선택이 곤란 <br>
- 시스템에 내재된 표준 페이스를 고려한 시간치 조정 단계 필요(인종, 연령, 성별 고려치 않아 실제 오차 존재) <br>
- 도입 초기 PTS 전문가 자문 필요 <br>
- 시스템 활용을 위한 교육 및 훈련 비용 발생 <br>
- 기계적으로 제어되는 동작시간에 적용 불가

주요 기법 비교 내용이다.

구분|정의|개발배경|복잡성/난이도|시간단위|Pace|정밀도/적용
-|-|-|-|-|-|-
WF|신체 각 부분 동작 난이도에 다라 서로 다른 개수로 work factor 부여|DWF 1945|복잡/쉬움|1RU(Ready time unit) = 0.001분|Incentive pace 125% rate|전자 및 기계조립 업체
MTM|작업에 필요한 기본 동작으로 분해하고 성질과 조건에 대응하는 시간치 부여|MTM1 1948, MTM2 1965, MTM3 1971| 간단, 약간 어려움|1TMU(Time measurement unit) = (1/100000)시간|Normal pace 100% rate|중공업
MODAPTS|신체 각 부분 동작 거리에 따라 시간치를 부여|Basic M 1966, Offixe M 1969, Tmnit M 1973|매우간단, 쉬움|1MOD(Modular) = 0.129/0.1초, 0.143/0.12초|4가지 pace임의로 채용|정밀기계, 가공업체

### 워크 샘플링

워크 샘플링(Work sampling)은 인간과 기계가 수행하는 여러가지 활동 시간과 유휴시간을 산정하는 기법이다. 스탑워치 시간연구법과는 달리 워크 샘플링은 활동 시간을 측정하지 않으며 활동 전 과정을 계속 지켜볼 필요도 없다. 관찰자가 작업자와 기계를 무작위적인 시간 간격으로 관찰하고 그 순간에 수행중인 활동 종류를 기록한다. 지연비율(ratio-delay), 즉 작업자가 어쩔 수 없이 지연되는 시간 비율이나 기계 유휴 시간비율을 분석하고 비반복적인 직무 분석을 위해 주로 사용된다. 워크 샘플링을 통해 구한 활동 시간 비율 추정치에는 어느 정도 오차가 발생하므로 이런 추정치를 그 활동에 실제 투입되는 시간 비율 근사치가 된다. 워크 샘플링 목표는 특정 신뢰 수준에서 일정한 오차 한계를 벗어나지 않는 추정치를 구하는 것이다.

$$
e = z\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}
$$

단,  

- $z$ = 목표 신뢰수준을 달성하기 위한 표준편차 수
- $\hat{p}$ = 표본 비율(발생횟수를 표본 크기로 나눈 값)
- $n$ = 표본 크기, $n = (\frac{z}{e})^2\hat{p}(1-\hat{p})$

절차
: 1. 조사 대상 작업자나 기계를 선정
1. 작업자나 감독자에게 조사 목적을 설명하여 의혹을 사지 않도록 함
1. 분석 담당자 경험이나 과거 자료를 사용하여 당장 사용할 비율 추정치 $\hat{p}$를 구하든지 그렇지 않으면 $\hat{p} = 0.5$를 초기값으로 사용하여 표본 크기를 계산
1. 무작위 관찰 계획 수립
1. 관찰을 시작하고 도중에 두어 차례 표본 크기 수정
1. 관찰하려는 특정 활동 시간 비율을 추정

### WF

**WF**(Work factor)법은 각 신체 부위마다 움직이는 거리, 취급중량, 작업자에 의한 제어 여부(동작 곤란) 등과 같은 변수에 대해 각 동작시간 표준치를 정하여 동작시간 표준을 적용하여 실질 시간을 구하는 기법이다. 인간이 하는 작업에는 그 작업 구성요소인 동작을 행하는 신체부위, 동작 크기, 동작 제약 외적 조건에 따라 동작 수행에 소요되는 객관적으로 적정한 시간이 존재한다는 전제에서 측정한다. 따라서 각 요소 동작마다 각 신체 부위별로 동작시간을 실제 데이터에 의해 제약요인과 관렩지어 해석하고 시간표를 만들어 둔다. 측정 단위 시간은 WFU며, 1분 = 10,000WFU이다.

기본원리
: - 모든 작업 동작은 제한된 몇가지 기본 요소 동작으로 분해 가능
- 각각 기본 요소 동작은 일정한 표준 시간치를 가짐
- 작업 동작 총 소요시간은 기본 요소 동작에 대한 표준 시간 합계 시간이 됨

4가지 주요 변수(시간 변동 요인)
- 사용되는 신체부위
        - 손가락(F), 손(H), 앞팔선희(F8), 팔(A), 몸통(T), 다리(L), 발(FT), 머리회전(HT)
- 이동 거리
        - 1~100cm, 45~180도
- 중량 또는 저항
        - 저항이 커질수록 W -> WW -> WWW, 신체 부위별 W 계수 다름
- **동작 곤란성**
        - 일정한 정지(D), 방향 조절(S), 주의(P), 방향변경(U)

번호|표준요소|기호|동작내용
-|-|-|-
1-1|이동-뻗치다|R|손이나 팔 등 신체부위 위치를 바꿈
1-2|이동-옮긴다|M|물건을 이동시킴(또는 이동중에 유용한 이을 함)
2|잡는다|Gr|물체를 작업자 컨트롤하에 두는 동작
3|놓는다|RI|물체에서 신체부위를 분리하는 동작
4|앞에 놓다|PP|다음 목적에 알맞게 물체 방향을 바꾸는 동작
5|조립|Asy|2가지 물체를 조합 또는 정리하는 동작
6|사용|Use|공구 및 기계 등을사용하는 요소
7|분해|Dsy|조립된 물체를 풀어내는 동작
8|정신작용|Mp|눈, 귀, 뇌 및 신경계통을 사용하는 요소
9|대기|W|대기, 놓고 있는 상태
10|유지|H|물건을 들고 있거나 누르고 있는 상태

```{mermaid}
flowchart TB
00[WF 동작시간 표준] --- 01[WF 동작분석]
01 --- 기초동작 & WF
기초동작 --- 11[사용되는 신체부위] & 12[이동거리] & 13[동작 또는 저항] & 14[동작 곤란성]
01 --- 기초동작 & WF
WF --- 11[사용되는 신체부위] & 12[이동거리] & 13[동작 또는 저항] & 14[동작 곤란성]
```

사용방법
: - 표준요소 10가지로 구분 실시
- 구분된 표준 요서별로 사용 신체 부위, 이동거리, 중량 또는 저항과 동작 곤란성 요소를 조사하여 WF(W, S, P, U, D 순으로) 기록




