# 설비보전관리 {#sec-equipmnet-maintainance}

## 자주보전 7단계

:::{.callout-tip title="기출"}
97-2-3
:::

| 단계  | 명칭                       | 활동내용                                                                                          | **육성 단계\*** |
|-------|----------------------------|---------------------------------------------------------------------------------------------------|-----------------|
| 1단계 | 초기 청소                  | 설비 본체를 중심으로 먼지, 더러움을 완전히 없앤다.                                                | 1단계           |
| 2단계 | 발생원, 곤란부위 대책 수립 | 먼저, 더러움 발생원, 비산 방지나 청소, 급유 곤란 부위를 개선하고 청소, 급유 시간 단축을 도모한다. | 1단계           |
| 3단계 | 청소/급유/점검 기준 작성   | 단시간으로 청소/급유/점검을 확실히 할 수 있도록 행동 기준을 작성한다.                             | 2단계           |
| 4단계 | **총점검\*\***             | 점검 매뉴얼에 의한 점검기능교육과 총 점검 실시에 의한 설비 미흡을 적출 및 복원한다.               | 2단계           |
| 5단계 | 자주점검                   | 자주점검 체크 시트 작성, 실시로 오퍼레이션 신뢰성을 향상한다.                                     | 3단계           |
| 6단계 | 표준화                     | MTBF 분석 기록을 확실하게 해석하여 설비 개선을 꾀한다.                                            | 3단계           |
| 7단계 | 자주관리 확립              |                                                                                                   | 4단계           |

\*설비에 강한 오퍼레이터 육성 단계

:   1.  단계: 오퍼레이터가 설비 개선 사고 방식을 익히는 단계
    2.  단계: 오퍼레이터가 설비 기능 및 구조는 이해하는 단계
    3.  단계: 오퍼레이터가 설비 정밀도와 제품 품질 간 관계를 이해하는 단계
    4.  단계: 오퍼레이터가 설비 수리 가능한 단계

\*\*총점검 전개 방법

:   1.  총점검 매뉴얼 준비 - 준비활동 및 총점검 과목 및 항목 설정
    2.  총점검 매뉴얼에 대한 교육 실시 - 기계요소 총점검 대상 및 부위 작성
    3.  총검검 매뉴얼 보완 - 담당설비별, 부품별 총점검 매뉴얼 내용 보완 작성
    4.  총점검 체크시트 작성 - 담당설비별 총점검 실시를 위한 체크시트 작성
    5.  총점검 실시와 미결함 적출 및 개선 - 청소/급유/점검 기준 및 점검표 보완
    6.  점검 기능 체크 - 담당설비별 기계요소 기능 체크

------------------------------------------------------------------------

<br>

## 설비 보전 지표

대표적인 설비 보전 지표로 MTTR, MTBF, MTTF가 있다. 위 지표는 설비 보전 신뢰성 지표로 사용되고 설벼 효율을 극대화 하기 위한 척도로도 사용된다.

### MTTR {#sec-mttr}

**MTTR**(mean time to repair)는 평균 수리 시간(평균 고장/장애 복구 시간)으로서 설비 고장이 발생했을 때부터 다시 동작하는데까지 걸리는 시간이다.

$$
MTTR = \frac{설비 정지 총 시간}{설비 정지 횟수}
$$

MTTR은 설비가 정상동작하지 않는 시간 총합을 측정하고 총 건수로 나눈 값으로 현장에서는 설비 보전성 지료로 사용된다.

<br>

### MTBF {#sec-mtbf}

**MTBF**(mean time between failures)는 평균 무고장 시간으로 설비가 한번 고장이 발생한 뒤 같은 고장이 다시 발생할 때까지의 평균 시간이다.

$$
MTBF = \frac{정상가동총시간}{고장횟수}
$$

설비 고장에 대한 대응력을 확인할 수 있는 지표로 설비 신뢰정 지표로 사용된다. MTBF는 수리 가능한 설비에 대한 지표이며, 수리가 불가한 설비나 시스템인 경우 MTTF를 사용해야 한다.

<br>

### MTTF {#sec-mttf}

**MTTF**(mean time to failures)는 수리하지 않은 부품이 사용되었을 때 시작 시점부터 고장 발생 시까지 시간을 의미한다. 

$$
MTTF = 수리하지 \ 않은 \ 부품의 \ 사용 \ 시작부터 \ 고장까지 \ 시간
$$

<br>

### 가용도

가용도는 다음과 같이 계산된다.

$$
가용도 = \frac{MTTF}{MTBF}
$$

::: {#exm-availability}
## 가용도 계산

설비 부품 A가 10시간 만에 파손되어 설비 고장이 발생하였고, 부품 A를 교체하는데 1시간 소요되었다. 교체된 부품 A가 다시 10시간 후 파손되었을 때 가용도를 계산하시오.
:::

설비 보전 지표는 다음과 같다.

- MTTR: 1
- MTTF: 10
- MTBF: 11 (10+1)

따라서 가용도는 다음과 같다.

$$
가용도 = \frac{MTTF}{MTBF} = 10/11 = 0.91
$$

해당 설비를 사용하는 작업장의 조업일수가 200일인 경우 200x0.09 = 18, 즉 18일은 비가동이라 볼 수 있다.

## 욕조곡선

::: {.callout-tip title="기출"}
97-4-3
:::

!!! 그림 추가

**욕조곡선**(bathtube curve), 신뢰도 곡선은 고장률이 시간 변화에 따라 높은 값에서 점차 낮은 값으로 감소하는 일정한 값을 얼마동안 유지한 후 점차 다시 높아지는 제품 수명을 나타내는 곡선이다. 신뢰도에서 고장률이 마치 욕조처럼 생겼다고 붙여진 명칭이다.

DFR, decrease failure rate
: - 초기고장, 감소형
- 품질관리 미비로 발생할 수 있는 고장으로 작업시작 전 점검, 시운전 등으로 사전 예방이 가능한 고장
- debugging 기간, burn-in 기간을 통해 결함 탐지 및 안정화

CFR, constant failure rate
: - 우발고장, 일정형
- 예측할 수 없는 경우 발생하는 고장으로 시운전이나 점검으로 예방이 불가
- 낮은 안전계수, 사용자 과오 등

IFR, increase failure rate 
: - 마모고장, 증가형
- 정치 일부분이 수명을 다하여 발생하는 고장
- 부식, 마모, 불충분한 정비 등 

### 고장률

**고장률**(failure rate)이란 어떤 시점까지 동작하여 온 품목이 계속되는 단위시간 내 고장을 일으키는 비율을 뜻한다. 평균 고장률은 총 고장횟수를 총 동작시간으로 나눈 값이다.

$$
평균고장률(\lambda) = \frac{r(총고장횟수)}{T(총동작시간)} = \frac{1}{MTBF}
$$

여기서 **[-@sec-mtbf]**(Mean Time Between Failure)는 평균고장간격으로, 즉 수리할 수 있는 시스템 또는 설비에서 고장 발생 시점부터 다음 고장 발생 시점까지의 평균 시간이다.

## RAMS

**RAMS**(Reliability, Availability, Maintainability, Safety)는 제품 신뢰성과 안전성 평가를 위한 지표이다. 제품이나 시스템의 신뢰성, 가용성, 유지보수성 그리고 안전성을 평가한다.

```{mermaid}
flowchart TB
RAMS --- 신뢰성 & 가용성 & 유지보수성 & 안전성
```

신뢰성(reliability)
: - 제품이 일정 기간 동안 얼마나 정상적으로 동작하는지를 나타내는 지표
- 고장없이 예상대로 동작하는 능력

가용성(availability)
: - 제품이나 시스템이 사용 가능한 상태에 있는 비율을 나타내는 지표
- 장애로 인한 중단 시간을 최소화하여 시스템 가동 시간을 최대한 확보하는 것이 목표

유지보수성(maintainability)
: - 제품이나 시스템이 고장 났을 때 빠르게 복구 또는 유지보수를 수행할 수 있는지를 나타내는 지표
- 유지보수성이 높으면 고장 시간을 최소화하고 장애복구를 빠르게 수행 가능

안전성(safety)
: - 제품이나 시스템을 사용하는 중 사용ㅈ바나 환경에 어떠한 유해한 영향도 미치지 않는 능력
- 제품 사용자와 주변 환경을 보호하는 중요한 역할

### 측정 방법

항목 | 측정방법
-|-
신뢰성 | MTBF, 실페 확률(특정 기간 내 고장이 발생할 확률, 과거 데이터 및 통계 기반으로 계산) 
가용성 | MTTR
유지보수성 | 복구 시간, 유지 보수 작업 복잡성, 필요한 기술 및 장비 등을 고려하여 평가
안전성 | HAZOP(hazard and operability study), FMEA(failure modes and effects analysis), FTA(fault tree analysis)
