# 설비계획 및 관리 {#sec-equipment-planning-management}

## 강제열화와 자연열화

#97-1-10

```{mermaid}
flowchart TB
열화 --- 강제열화 & 자연열화
```

**강제열화**는 설비에 대해서 당연 해야 할 일을 하지 않기 때문에, 즉 인위적으로 열화를 촉진되는 현상이다. 급유해야 할 개소에 급유를 하지 않는다든지 급유량이 기준에 못 미치는 등이 여기에 해당한다.

이에 반해 **자연열화**는 설비를 올바르게 사용하고 있어도 시간과 함게 물리적으로 열화하여 초기 성능 대비 저하되는 현상이다. 

## 설비종합효율

#97-3-2

**설비종합효율**(Overall Equipment Effectiveness, OEE)은 실행 예정 기간 동안 제조 작업이 최대 잠재력과 비교하여 얼마나 잘 활용되는지(시설, 시간 및 재료)를 측정한 값이다. 이는 실제로 생산적인 제조 시간 비율을 식별한다. 100% OEE는 최대 속도(100% 성능)로 중단 없이(100% 가용성) 좋은 부품만 생산(100% 품질)한다는 의미이다. [^4-1-oee]

[^4-1-oee]: https://ko.wikipedia.org/wiki/설비종합효율

### 설비종합효율 용어

조업시간
: - 1일 근무시간을 기초로 하루 시업 시간과 종업 시간 사이 총시간으로 휴식, 식사, 수주물량 부족 등 **계획 정지시간을 포함**한다.

부하시간
: - 조업시간에 기업이 인정하는 식사시간, 휴식시간을 제외하고 설비가 실제 가동되어야 할 시간이다.
- $부하시간 = 조업시간 - 계획정지시간$

가동시간
: - 설비 부하시간에서 정지시간을 제외한 시간으로 설비가 실제 가동한 시간이다. 정지시간이란 비계획적으로 설비가 일정시간(예 5분) 이상 가동하지 않는 시간이다.
- $가동시간 = 부하시간 - 정지시간$

실가동시간
: - 설비가 현재 성능으로 얼마나 제품 생산에 기여했는지를 나타내는 시간이다.
- $실가동시간 = 생산량 \times 실제 cycle time$

성능가동시간
: - 설비 도입 시 표준 성능으로 얼마나 제품을 생산 가능한지를 나타내는 시간이다.
- $성능가동시간 = 생산량 \times 이론 cycle time$

가치가동시간
: - 설비 도입 시 성은으로 얼마나 양품을 생산했는지를 나타내는 시간이다. 
- $가치가동시간 = 양품수 \times 이론 cycle time$

### 설비종합효율 산출

설비종합효율은 기업에서 규정한 부하시간 중 설비 고유 성능을 가지고 부가가치를 만들어 낸 시간 비율을 뜻한다.

$$설비종합설비 = 시간 가동률 \times 성능 \times 가동률 양품률$$

시간가동률
: - 부하시간 중 설비 고장정지, 기종변경, 자재 품절, 유실 시간 등을 제외한 가동시간과 부하시간 간 비율로 설비가 정지 없이 가돋되고 있는가를 나타내는 지표이다.
- $시간가동률 = \frac{부하시간 - 정지시간}{부하시간} \times 100$

성능가동률
: - 가동시간 중 설비 목표 성능을 바뤼한 시간 비율이다.
- $성능가동률 = \frac{생산량 \times 이론 cycle time}{가동시간} \times 100$

양품률
: - 전체 생산 수량에서 양품 비율을 나타낸다.
- $양품률 = \frac{생산수량 - 불량수량}{생산수량} \times 100$

내용|집계결과
-|-
부하시간|5700분
고장정지시간|100분
고장발생건수|3회
준비교체시간|390분
총생산량|4250개
부적합(불량)품수|250개
이론속도/개|1.0분/개
실제속도/개|1.2분/개
: 공장관리기술사 97회 예제 {#tbl-97-3-2}

위 표([-@tbl-97-3-2]) 기준으로 설비종합효율을 계산하면 다음과 같다.

$시간가동률 = \frac{부하시간 - 정지시간}{부하시간} \times 100 = \frac{5700 - (100 + 390)}{5700} \times 100 = 91.4(\%)$

$성능가동률 = \frac{생산량 \times 이론 cycle time}{부하시간-정지시간} \times 100 = \frac{4250 \times 1}{5700 - (100 + 390)} \times 100 = 81.6(\%)$

$양품률 = \frac{총생산량-불량품수}{총생산량} \times 100 = \frac{4250-250}{4250} \times 100 = 94.1(\%)$

따라서 종합설비효율은 다음과 같다.

$$OEE = 시간가동률 \times 성능가동률 \times 양품률 = 91.4 \times 81.6 \times 94.1 = 70.2(\%)$$

