# 설비계획 및 관리 {#sec-equipment-planning-management}

## 강제열화와 자연열화

:::{.callout-tip icon=false title="기출"}
97-1-10
:::

```{mermaid}
flowchart TB
열화 --- 강제열화 & 자연열화
```

**강제열화**는 설비에 대해서 당연 해야 할 일을 하지 않기 때문에, 즉 인위적으로 열화를 촉진되는 현상이다. 급유해야 할 개소에 급유를 하지 않는다든지 급유량이 기준에 못 미치는 등이 여기에 해당한다.

이에 반해 **자연열화**는 설비를 올바르게 사용하고 있어도 시간과 함게 물리적으로 열화하여 초기 성능 대비 저하되는 현상이다. 

## 설비종합효율

:::{.callout-tip icon=false title="기출"}
97-3-2, 109-3-5
:::

**설비종합효율**(Overall Equipment Effectiveness, OEE)은 실행 예정 기간 동안 제조 작업이 최대 잠재력과 비교하여 얼마나 잘 활용되는지(시설, 시간 및 재료)를 측정한 값이다. 이는 실제로 생산적인 제조 시간 비율을 식별한다. 100% OEE는 최대 속도(100% 성능)로 중단 없이(100% 가용성) 좋은 부품만 생산(100% 품질)한다는 의미이다. [^4-1-oee]

[^4-1-oee]: https://ko.wikipedia.org/wiki/설비종합효율

### 설비종합효율 용어

조업시간
: - 1일 근무시간을 기초로 하루 시업 시간과 종업 시간 사이 총시간으로 휴식, 식사, 수주물량 부족 등 **계획 정지시간을 포함**한다.

부하시간
: - 조업시간에 기업이 인정하는 식사시간, 휴식시간을 제외하고 설비가 실제 가동되어야 할 시간이다.
- $부하시간 = 조업시간 - 계획정지시간$

가동시간
: - 설비 부하시간에서 정지시간을 제외한 시간으로 설비가 실제 가동한 시간이다. 정지시간이란 비계획적으로 설비가 일정시간(예 5분) 이상 가동하지 않는 시간이다.
- $가동시간 = 부하시간 - 정지시간$

실가동시간
: - 설비가 현재 성능으로 얼마나 제품 생산에 기여했는지를 나타내는 시간이다.
- $실가동시간 = 생산량 \times 실제 cycle time$

성능가동시간
: - 설비 도입 시 표준 성능으로 얼마나 제품을 생산 가능한지를 나타내는 시간이다.
- $성능가동시간 = 생산량 \times 이론 cycle time$

가치가동시간
: - 설비 도입 시 성은으로 얼마나 양품을 생산했는지를 나타내는 시간이다. 
- $가치가동시간 = 양품수 \times 이론 cycle time$

### 설비종합효율 산출

설비종합효율은 기업에서 규정한 부하시간 중 설비 고유 성능을 가지고 부가가치를 만들어 낸 시간 비율을 뜻한다.

$$설비종합설비 = 시간 가동률 \times 성능 \times 가동률 양품률$$

시간가동률
: - 부하시간 중 설비 고장정지, 기종변경, 자재 품절, 유실 시간 등을 제외한 가동시간과 부하시간 간 비율로 설비가 정지 없이 가돋되고 있는가를 나타내는 지표이다.
- $시간가동률 = \frac{부하시간 - 정지시간}{부하시간} \times 100$

정미가동률
: - 실제 생산 시간 대비 가동시간 비율이다.
- $정미가동률 = \frac{생산량 \times 실제 cycle time}{부하시간 - 정지시간} \times 100$

속도가동률
: - 이론 cycle time 대비 실제 cycle time비율이다.
- $속도가동률 = \frac{이론 cycle time}{실제 cycle time} \times 100$

성능가동률
: - 가동시간 중 설비 목표 성능을 바뤼한 시간 비율이다.
- $성능가동률 = \frac{생산량 \times 이론 cycle time}{가동시간} \times 100$
- $성능가동률 = 정미가동률 \times 속도가동률 = \frac{생산량 \times 실제 cycle time}{부하시간 - 정지시간} \times \frac{이론 cycle time}{실제 cycle time}$

양품률
: - 전체 생산 수량에서 양품 비율을 나타낸다.
- $양품률 = \frac{생산수량 - 불량수량}{생산수량} \times 100$
  
<br>

예제
: > 
내용|집계결과
-|-
부하시간|5700분
고장정지시간|100분
고장발생건수|3회
준비교체시간|390분
총생산량|4250개
부적합(불량)품수|250개
이론속도/개|1.0분/개
실제속도/개|1.2분/개

  
설비종합효율을 계산하면 다음과 같다.

$시간가동률 = \frac{부하시간 - 정지시간}{부하시간} \times 100 = \frac{5700 - (100 + 390)}{5700} \times 100 = 91.4(\%)$

$정미가동률 = \frac{생산량 \times 실제 cycle time}{부하시간 - 정지시간} \times 100 = \frac{4250 \times 1.2}{5700 - 100 - 390} \times 100 = 97.9(\%)$

$속도가동률 = \frac{이론 cycle time}{실제 cycle time} \times 100 = \frac{1.0}{1.2} \times 100 = 83.3(\%)$

$성능가동률 = \frac{생산량 \times 이론 cycle time}{부하시간-정지시간} \times 100 = \frac{4250 \times 1}{5700 - (100 + 390)} \times 100 = 81.6(\%)$
  
$양품률 = \frac{총생산량-불량품수}{총생산량} \times 100 = \frac{4250-250}{4250} \times 100 = 94.1(\%)$


따라서 종합설비효율은 다음과 같다.

  
$$OEE = 시간가동률 \times 성능가동률 \times 양품률 = 91.4 \times 81.6 \times 94.1 = 70.2(\%)$$

## 공정설비계획

:::{.callout-tip icon=false title="기출"}
106-3-3
:::

:::{.callout-important icon=false title="설비 수량 계산"}

구분|표준작업시간|효율|신뢰도
-|-|-|-
공정1|4분|93%|95%
공정2|5분|95%|90%

문제1
: 1일 8시간, 1주 5일간 작업하여 주당 2,000개 제품을 생산하려 한다. 표를 참고하여 생산 목표를 달성하기 위해필요한 공정 1과 공정 2에 대한 기계대수를 각각 구하시오.

문제2
: 제품 A는 공정 1과 공정 2를 거쳐 생산되며, 공정 1 불량률은 5%, 공정 2 불량률은 3%이다. 양품 1,000개 생산을 목표로 할 때 공정 1에대한 원자재 투입량을 구하시오.

문제3
: 제품 A에 대한 공정 1 공정비용은 개당 1,000원, 공정 2 공정비용은 개당 2,000원이다. 공정 2를 거친 완성품은 전수검사를 하며 완성품 검사비용은 개당 100원이다. 공정 1과 공정 2 사이 공정간 검사비용은 80원인 경우, 공정 간 검사를 실시하는 것이 경제적 측면에서 유리한지 판단하시오.

----

문제1
: - 기계능력 = 유효가동시간 x 기계대수 = 가동일수 x 1일 가동시간 x 가동률 x 기계대수
- 공정1
$$
기계대수 = \frac{2000개 \times 4분}{5일/주 8시간/일 \times 60분/시간 \times (.093 \times 0.95) = 3.8대}
$$
- 공정2
$$
기계대수 = \frac{2000개 \times 5분}{5일/주 8시간/일 \times 60분/시간 \times (.095 \times 0.90) = 4.9대}
$$

따라서, 공정1은 4대, 공정2는 5대 기계설비가 필요하다.

문제2
: - 원자재 투입량 x (0.95 x 0.97) = 1000(개)

따라서 양품 1,000개를 생산하기 위한 원자재 투입량은 1,086개이다.

문제3
: - 공정별 Lot 크기
        - 원자재 투입량 1086 -> 공정1 불량률 5% 시 1032 -> 공정2 불량률 3% 시 1000
- 전수검사 시 비용: 366,000(원)
        - 전수검사 비용: 1086 x 100 = 108,600
        - 불량 생산 비용: 86 x (1,000 + 2,000) = 258,000
- 공정검사 시 비용: 308,080(원)
        - 공정1 검사 비용: 1,086 x 80 = 86,880
        - 공정2 검사 비용: 1032 x 100 = 103,200
        - 불량 생산 비용 = (54 x 1,000) + (32 x 2000) = 118,000

따라서 공정검사를 실시하는 것이 전수검사를 실시하는 것보다 경제적으로 유리하다.

:::

## 기계설비 위험점

:::{.callout-tip icon=false title="기출"}
115-1-9
:::

기계설비에 형성되는 위험점 6가지
: - 협착점
        - 왕복운동하는 동작부분과 고정부분 사이에 형성되는 위험점
        - 프레스, 전단기, 굽힘기계 등
- 끼임점
        - 고정부분과 회전 또는 직선운동하는 부분 사이에 형성되는 위험점
        - 외전 풀리와 베드 사이, 연삭숫돌과 작업대, 핸들과 고정대 사이, 교반기 날개와 하우스 등
- 절단점
        - 회전하는 운동부 자체 위험이나 운동하는 기계 자체 위험에서 형성되는 위험점
        - 밀링커터, 둥근 톱날 등
- 물림점
        - 서로 반대방향으로 회전하는 두 개 회전체가 맞닿아서 생기는 위험점
        - 기어, 롤러
- 접선물림점
        - 회전하는 부분 접선방향으로 물려 들어갈 위험이 존재하는 위험점
        - 풀리와 벨트, 체인과 스프라켓, 기어와 벨트 등
- 회전말림점
        - 회전하는 물체 길이 등이 불규칙한 부위와 돌기 회전부 위에 옷, 장값 등이 말려 드는 위험점
        - 회전축, 드릴 등














