# 작업방법 및 시간 연구 {#sec-motion-time-study}

::: {.callout-tip icon=false title="기출"}
100-1-5, 109-3-2
:::

## 워크샘플링 {#sec-work-sampling}

**워크샘플링**(work sampling)법은 확률을 기반으로 최소한 샘픙을 순간적으로 관측하여, 관측 대상으로 하는 현장 전체 모습을 실용상 만족할만한 신뢰구간과 정확도를 가지고추정하는 작업측정 기법이다.

장점
: - 내용이나 실시 절차가 복잡하지 않기 때문에 관측 담당자에 대한 고도 훈련이 필요치 않다.
- 비용면에서도 시간 연구법에 비해 저렴하다.
- 작업자에게 주는 심리적 압박을 배제할 수 있다.

단점
: - 작업을 요소별로 분할해서 관측할 수 없다.
- 관측결과 오차가 시간연구법보다 크다.

워크샘플 표준시간 선정 절차
: 1. 관측 대상과 목적을 정한다.
2. 특정 활동 발생률(유휴율 내지 가동률)을 추정한다.
3. 관측에서 요구되는 신뢰수준과 정확도(오차율)를 정한다.
4. 관측이 행해질 관측시간을 랜덤으로 정한다.
5. 조사기간 중 두세 차례에 걸쳐 필요한 관측 수를 재계산하여 조정한다.
6. 관측겨로가에 의해서 정상시간과 표준시간을 산성한다.

워크샘플링 표준시간 계산 방법
: 1. 관측수(N) 결정, $N = (\frac{K}{S})^2\frac{1-p}{p}$
        - N: 랜덤 관측 횟수(샘플 크기)
        - K: 신뢰수준에 따라 정해지는 표준편차 배수
        - S: p에 대한 상대적 정도(허용오차)
        - p: 구하는 비율(발생률)
2. 표준시간 산정
        - $정상시간(단위당)=\frac{총관측시간x발생률x수행도평가(레이팅)}{생산량}$
        - 여기서 여유시간을 가산하여 단위당 표준시간 산정
            - 표준시간 = 정상시간(1+여유률)
            - 표준시간 = 정상시간 x $(frac{1}{1-여유율})$

워크샘플링 적용 대상
: - 시간연구법으로 적용하기 어려운 비반복적인 업무에 효과적
- 기계수리, 세탁, 토목공사 등과 같은 업무에 활용

## 동작경제원칙

**동작경제원칙**(Principle of motion economy)은 작업 효율성을 향상시키기 위해 인간 동작을 최소화하고 최적화하는 원칙이다. 주로 산업공학, 작업설계 및 생산성 향상 분야에서 사용되며 사람 동작을 더 빠르고 효율적으로 만들기 위해 다양한 기술적, 물리적 방법을 제시한다.

이 원칙은 Frank B. Gilbreth와 Lillina M. Gilbreth 부부가 20세기 초에 개발한 동작연구(Motion study)에서 유래했다. 사람 동작을 분석하고 불필요한 동작을 제거함으로써 작업 효율을 높이고 피로도를 줄이며 생산성을 향상시키는 ㅂ아법을 제시했다.

동작경제원칙 핵심 요소
: - 동작 간소화: 동작을 수행하는데 필요한 동작 수를 줄인다. 즉 한번에 두개 이상 동작을 동시에 하거나 불필요한 동작을 피할 수 있도록 설계한다.
- 동작 효율성: 동작은 최대한 자연스럽고 효율적으로 이루어져야 하며, 불필요하게 힘을 주거나 긴 시간을 소요하는 동작은 피해야 한다.
- 동작 표준화: 사람마다 작업 동작에 차이가 있을 수 있는데, 가장 효율적으로 표준화된 동작 방법을 설정하여 모든 작업자가 동일한 방식으로 작업을 수행하게 한다.
- 동작 순서화: 작업을 할 대 동작 순서를 논리적이고 일관되게 배치하여 작업자가 불필요하게 멈추거나 돌아가지 않도록 한다.
- 도구와 장비 최적화: 작업에 필요한 도구와 장비는 손쉽게 접근할 수 있도록 배치하며, 불필요한 움직임을 최소화하는 디자인을 적용한다.

동작경제원칙 장점
: - 생산성 향상: 불필요한 동작을 줄이고 효율적인 작업 흐름을 만들어 생산성을 높일 수 있다.
- 피로감 감소: 불필요한 움직임을 최소화하면 작업자 피로도가 줄어들어 더 우래 작업이 가능하다.
- 비용 절감: 작업 시간이 단축되고, 인력 효율성이 높아져 인건비나 운영 비용이 절감될 수 있다.
- 안전성 향상: 효율적인 동작 설계를 통해 작업 중 사고나 부상 위험을 줄일 수 있다.

F.B. Gilbreth가 처음 사용하고 반즈(R.M. Banrnes)가 개량 보와한 동작경제 3원칙은 다음과 같다.

동작경제 3원칙
: 1. 신체 사용에 관한 원칙
2. 작업역 배치에 관한 원칙
3. 공구 및 설비 설계에 관한 원칙

### 신체 사용에 관한 원칙

:::{.callout-tip icon=false title="기출"}
109-1-2
:::

신체 사용에 있어 다음과 같은 원칙이 있다.

1. 양손은 동시에 동작을 시작하고 또 끝마쳐야 한다.
2. 휴식시간 이외에 양손이 동시에 노는 시간이 있어서는 안 된다.
3. 양팔은 각기 반대방향에서 대칭적으로 동시에 움직여야 한다.
4. 손의 동작은 작업을 수행할 수 있는 최소동작 이상을 해서는 안 된다.
5. 작업자들을 돕기 위하여 동작의 관성을 이용하여 작업하는 것이 좋다.
6. 구속되거나 제한된 동작 또는 급격한 방향전환보다는 유연한 동작이 좋다.
7. 작업동작은 율동이 맞아야 한다.
8. 직선동작보다는 연속적인 곡선동작을 취하는 것이 좋다.
9. 탄도동작(ballistic movement)은 제한되거나 통제된 동작보다 더 신속, 정확, 용이하다.
10. 눈을 주시시키는 동작 또는 이동시키는 동작은 되도록 적게 하여야 한다.

### 작업역 배치에 관한 원칙

1. 모든 공구와 재료는 일정한 위치에 정돈되어야 한다.
2. 공구와 재료는 작업이 용이하도록 작업자의 주위에 있어야 한다.
3. 재료를 될 수 있는 대로 사용위치 가까이에 공급할 수 있도록 중력을 이용한 호퍼 및 용기를 사용하여야 한다.
4. 가능하면 낙하시키는 방법을 이용하여야 한다.
5. 공구 및 재료는 동작에 가장 편리한 순서로 배치하여야 한다.
6. 채광 및 조명장치를 잘 하여야 한다.
7. 의자와 작업대의 모양과 높이는 각 작업자에게 알맞도록 설계되어야 한다.
8. 작업자가 좋은 자세를 취할 수 있는 모양, 높이의 의자를 지급해야 한다.

### 공그 및 설비 설계에 관한 원칙

1. 치구, 고정장치나 발을 사용함으로써 손의 작업을 보존하고 손은 다른 동작을 담당하도록 하면 편리하다.
2. 공구류는 될 수 있는 대로 두 가지 이상의 기능을 조합한 것을 사용하여야 한다.
3. 공구류 및 재료는 될 수 있는 대로 다음에  사용하기 쉽도록 놓아 두어야 한다.
4. 각 손가락이 사용되는 작업에서는 각 손가락의 힘이 같지 않음을 고려하여야 할 것이다.
5. 각종 손잡이는 손에 가장 알맞게 고안함으로써 피로를 감소시킬 수 있다.
6. 각종 레버나 핸들은 작업자가 최소의 움직임으로 사용할 수 있는 위치에 있어야 한다.







