# 품질관리 {#sec-quality-management}

## 관리도

::: {.callout-tip title="기출"}
97-4-5, 103-3-5
:::

**관리도**(Shewhart Chart)는 <font color="blue">통계적인 품질관리 도구</font>로써 자료 분포와 시계열 특성을 동시에 다룬다. 제조 및 경영 프로세스에 있어 통계적 관리 상태 여부 판별을 위한 관리지원 도구 중 하나이다.

변동요인
: - 우연요인(일상원인, 공통원인 by Deming)
    - 불가피한 원인, 제거 불가능(경제적 관점)
    - 재료, 기기, 작업자 변동(통제 불가능한 수준)
- 이상원인(특별원인 by Deming)
    - 체계가 관리상태가 아닌 경우
    - 관리도 주요 관심 대상

### 관리도 종류

사용 목적에 따라 공정 해석용 관리도와 공정 관리용 관리도로 분류할 수 있다. 이는 표준값이 주어져 있느냐에 따라 구분이 가능하다.

관리도 분류
:   -   해석용 관리도
    -   관리용 관리도


+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 해석용 관리도                                                                                                                                                                    | 관리용 관리도                                                                                                                                                                             |
+==================================================================================================================================================================================+===========================================================================================================================================================================================+
| -   공정상태가 어떤지 모르는 상황에서 공정 실태를 파악하여 어떤 원인에 의해 어떠한 산포가 발생하는지 알아 볼 목적으로 작성하는 관리도                                            | -   관리도를 지속적으로 작성해 나가면서 그 때마다 공정을 해석하고 만일 이상이 나타나면 그 즉시 원인을 조사하여 합당한 조치를 취해줌으로써 공정을 안정상태로 유지하기 위해 작성하는 관리도 |
|                                                                                                                                                                                  |                                                                                                                                                                                           |
| -   관리한계(UCL, LCL)선을 점선(⋯)으로 표시                                                                                                                                      | -   관리한계(UCL, LCL)선을 일점쇄선(- ⋅ - ⋅ -)으로 표시                                                                                                                                   |
|                                                                                                                                                                                  |                                                                                                                                                                                           |
| -   표준값이 주어져 있지 않기 때문에 수집된 데이터를 통하여 중심선과 관리한계선을 계산하여 사용하며, 공정이 관리상태로 안정되면관리한계선을 연장하여 관리용 관리도 한계선을 사용 | -   이전 안정된 상태 관리한계선을 바탕으로 현재 공정을 비교함으로써 공정 변화를 빠르게 점검 가능                                                                                          |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

<br>

```{mermaid}
flowchart TB

31["xbar - R<br>xbar - s"]
33["xtilde - R<br>(Me - R)"]
35["X - Rs"]
37["x - xbar - R"]

subgraph sg6[<br><br><br><br><br><br><br><br><br><br><br>포아송분포]
24
c
u
end

subgraph sg5[<br><br><br><br><br><br><br><br><br><br><br>이항분포]
23
np
p
end

subgraph sg0[<br><br><br><br><br><br><br><br><br><br><br>정규분포]
22
21
31
33
35
37
end
23 -- 일정 --> np
23 -- 불일정 --> p


24 -- 일정 --> c
24 -- 불일정 --> u

22 -- 가능 --> 37
22 -- 불가능 --> 35
21 --"xbar"--> 31
21 --"xtilde(Me)"--> 33

01{"품질 특성값"} -- 계량값 --> 11{"군 크기"}
01 -- 계수값 --> 12{"판단"}

11 -- "한 개" --> 22{"군 구분"}
11 -- "여러 개" --> 21{"중심선"}

12 --부적합품 --> 23{"군 크기"}
12 --부적합--> 24{"군 단위"}

```

계수형(계수치)
: - 연속량으로 측정되는 품질 특성 값(예, 길이, 무게, 온도, 전류 등)

계량형(계량치)
: - 유효한 값으로 표시되는 수치 값(예, 1개, 2개 등 이산적으로 셀 수 있는 값)

군 크기
: - 하나의 통일된 군(집단)을 구성하는 개체 수 

## 관리도 작성

### 계량형 관리도

관리도|측정치|CL|UCL|LCL|측정치|CL|UCL|LCL
-|-|-|-|-|-|-|-|-
$x-R$|$\bar{x}$|$\bar{\bar{x}}$|$\bar{\bar{x}} + A_2\bar{R}$|$\bar{\bar{x}} - A_2\bar{R}$|$R$|$\bar{R}$|$D_4\bar{R}$|$D_3\bar{R}$
$\bar{x}-R$|$\bar{x}$|$\bar{\bar{x}}$|$\bar{\bar{x}} + E_2\bar{R}$|$\bar{\bar{x}} - E_2\bar{R}$|$R$|$\bar{R}$|$D_4\bar{R}$|$D_3\bar{R}$
$x-s$|$\bar{x}$|$\bar{\bar{x}}$|$\bar{\bar{x}} + A_3\bar{R}$|$\bar{\bar{x}} - A_3\bar{R}$|$s$|$\bar{s}$|$B_4\bar{s}$|$B_3\bar{s}$

### 계수형 관리도

관리도 | 측정치 | CL | UCL | LCL
-|-|-|-|-
$p$ | $p$ | $\bar{p}$ | $\bar{p}+3\sqrt{\frac{\bar{p}(1-\bar{p})}{n}}$ | $\bar{p}-3\sqrt{\frac{\bar{p}(1-\bar{p})}{n}}$
$np$ | $np$ | $n\bar{p}$ | $n\bar{p} + 3\sqrt{n\bar{p}(1-\bar{p})}$ | $n\bar{p} - 3\sqrt{n\bar{p}(1-\bar{p})}$
$u$ | $u$ | $\bar{u}$ | $\bar{u} + 3\sqrt{\frac{\bar{u}}{n}}$ | $\bar{u} - 3\sqrt{\frac{\bar{u}}{n}}$
$c$ | $c$ | $\bar{c}$ | $\bar{c} + 3\sqrt{\bar{c}}$ | $\bar{c} - 3\sqrt{\bar{c}}$

## 관리도 해석

현상|설명|ISO7870-2:2013|AT&T
-|-|-|-
이탈|관리한계선을 벗어남|#1|#1
치우침| 7개 연속으로 중심선 한 쪽에서 있음(AT&T 9개) | #2 | #2
경향 | 7개 연속으로 증가(또는 감소)(AT&T 6개) | #2 | #2
주기성| 주기성이 나타남(AT&T 14개 연속 지그재그) | #4 | #4
경계1 | 3개 중 2개 A 영역 | - | #5
경계2 | 5개 중 4개 A,B 영역 | - | #6
과집중 | 15개 연속 C 영역 | - | #7
경계3 | 8개 연속 B 영역 | - | #8

영역
: - A: CL $\pm 1\sigma$
- B: $\pm1 \sim \pm2 \sigma$
- C: $\pm2 \sim \pm3 \sigma$

:::{.callout-important title="$\bar{X}-R$ 관리상한선/중심선/관리하한선 계산"}

제품규격이 $750 \pm40mm$이고, 측정결과 k=16, n=5, $\sum{\bar{X}}=12,137.8$, $\sum{R}=628$
n=5일 때, $A$ = 1.342, $A_2$=0.577, $D_2$=4.918, $D_4$=2.114, $d_2$=2.326

$\bar{X}$ 관리도
: - $CL = \bar{\bar{x}} = \frac{\sum\bar{x}}{k} = \frac{12137.8}{16} = 758.61$
- $UCL = \bar{\bar{x}} + A_2\bar{R} = 758.61 + 0.577 \times 39.25 = 781.26$
- $LCL = \bar{\bar{x}} + A_2\bar{R} = 758.61 - 0.577 \times 39.25 = 735.97$

R관리도
: - $CL = \frac{\bar{R}}{k} = \frac{628}{16}=39.25$
- $UCL = D_4\bar{R} = 2.114 \times 39.25 = 82.97$
- $LCL = D_3\bar{R}$ = (음수이므로 고려하지 않음)
:::

## 공정능력지수 {#sec-cpk}

:::{.callout-tip icon=false title="기출"}
112-1-7
:::


**공정능력지수**(Process Capability Index)는 산포와 규격 간 상대적 크기를 나타내는 지표이다.

산포
: - 공정 결과물 분포, $\mu \pm 3\sigma$, 좁을수록 좋음

규격
: - 제품 특성 범위, LSL ~ USL로 고정됨

$$
C_p = \frac{USL - LSL}{6\sigma}
$$

$$
C_pk = (1-k)C_p, \quad k = |\frac{\frac{USL+LSL}{2}-\bar{x}}{\frac{USL-LSL}{2}}|
$$

:::{.callout-important title="공정지수계산"}

제품규격이 $750 \pm40mm$이고, 측정결과 k=16, n=5, $\sum\bar{X}=12,137.8$, $\sum{R}=628$
n=5일 때, $A$ = 1.342, $A_2$=0.577, $D_2$=4.918, $D_4$=2.114, $d_2$=2.326

$\bar{\bar{x}}$ = 12137.8/16 = 758.61이고 M = (790+710)/2 = 750이므로 산포가 USL측으로 치우침이 있다. 따라서 $C_{pk}$를 계산한다. 

$$
C_{pk} = (1-k)C_p = (1 - 0.21) \times \frac{790-710}{6 \times \frac{\bar{R}}{d_2}} = 0.62
$$

$$
k = \frac{|\bar{\bar{x}}-M|}{\frac{T}{2}} = \frac{758.61 - 750}{\frac{790-710}{2}} = 0.21
$$

판정
: - $C_{pk}$ = 0.62 < 0.67이므로 4등급 판정되며 공정능력이 매우 부족하다고 판단된다.
:::

:::{.callout-tip icon=false title="공정 부적합수 관리도"}
군(k)| 1| 2| 3| 4| 5| 6| 7| 8| 9| 10| 11| 12| 13| 14| 15
-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-
시료크기(n)|1.0|1.0|1.0|1.0|1.3|1.3|1.3|1.3|1.3|1.2|1.2|1.2|1.7|1.7|1.7
부적합수|2|5|3|2|1|5|2|4|2|6|4|1|8|3|8

관리한계선을 계산하고 관리도 작성 및 해석하시오.

----

주어진 데이터는 단위당 부적합수를 나타내므로 u관리도를 작성하여 공정을 해석한다. u관리도는 시료 면적이나 길이 등 일정하지 않을 때 사용하며, UCL과 LCL이 CL(중심선)을 기준으로 대칭적이고 계단식이 된다.

$$
CL = \bar{u} = \frac{\sum{c}}{\sum{n}} = \frac{56}{19.2} = 2.92
$$

단위 면적당 UCL과 LCL을 각각 계산한다. LCL 경우 음(-) 값이 되므로 고려하지 않는다.

n = 1.0일때
: 
$$
UCL = \bar{u} + 3\sqrt{\frac{\bar{u}}{n}} = 2.92 + 3\sqrt{\frac{2.92}{1.0}} = 8.04
$$

n = 1.2일때
: 
$$
UCL = \bar{u} + 3\sqrt{\frac{\bar{u}}{n}} = 2.92 + 3\sqrt{\frac{2.92}{1.2}} = 7.59
$$

n = 1.3일때
: 
$$
UCL = \bar{u} + 3\sqrt{\frac{\bar{u}}{n}} = 2.92 + 3\sqrt{\frac{2.92}{1.3}} = 7.41
$$

n = 1.7일때
: 
$$
UCL = \bar{u} + 3\sqrt{\frac{\bar{u}}{n}} = 2.92 + 3\sqrt{\frac{2.92}{1.7}} = 6.85
$$

모든 단위당 부적합품수가 관리상한선 내에 있으므로 관리상태에 있다고 판단할 수 있다.
:::

## 품질경영 4대 절대 조건

:::{.callout-tip title="기출" icon=false}
103-2-5
:::


P.B. Crosby 품질경영 4대 절대조건(Absolute of Quality Management)은 필립 Crosby가 품질관리 이론을 정립하면서 제시한 품질경영 핵심 원치이다. 품질은 "결함 없는 제품"이라는 개념으로 정의하며, 이를 다성하기 위한 4가지 절대 조건을 제시했다. 이 네가지 절대 조건은 품지 경영 실행과 평가를 위한 기본적인 원칙을 제공한다.

품질은 적합성(conformance to requirements)이다.
: - 품질이란 "고객 요구 사항과 사양에 부합하는지 여부"를 의미한다. 품질은 단순히 제품이나 서비스 특성이 아니라 **고객 요구와 기대를 정확히 충족시키는 것**이 핵심이다. 이는 품질을 결함없는 상태로 정의하는 개념과 연결된다.
- 품지은 "적합성", 즉 고객 요구를 충족하는 정도로 정의하며, 이를 기반으로 품질을평가한다.

품질은 예방해야 한다.
: - 품질을 향상시키는 가장 좋은 방법은 "**문제를 사전에 예방하는 것**"이다. Crosby는 품질이 결함을 피하는 데 집중해야 하며, 결함이 발생한 후 이를 수정하는 것보다는 결함이 발생하지 않도록 예방하는 데 초점을 맞춰야 한다고 강조했다.
- 이 원칙은 품질 관리가 단순히 문제를 해결하는 것이 아니라, **초기 설계와 개발 단계에서부터 품질을 고려하여 잠재적 결함을 방지**하는 데 중점을 두어야 한다는 것을 의미한다.

품질 측정은 "결함 없음"이다.
: - Crosby는 품질을 측정하는 방법을 "**결함 없음(zero defects)**" 으로 정의했다. 즉, 품질을 평가할 때 결함이 하나도 없다는 상태를 목표로 해야 한다는 것이다. 이때 결함이란 고객의 요구를 충족하지 못한 부분을 의미한다.
- 품질 관리는 "결함이 없다"고 판단될 때까지 개선하고, 이를 목표로 삼아야 한다. 결함 없는 상태가 품질의 지표이며, 결함이 없는 상태를 지향해야 한다는 점이 핵심이다.

품질을 위한 비용은 "무결점"을 만드는 데 드는 비용이 가장 경제적이다.
: - Crosby는 품질 개선을 위해서는 결함을 없애는 데 드는 비용이 결국 가장 적게 든다고 주장했다. 즉, 품질 관리에서의 비용은 결함을 발견하고 수정하는 비용보다, 초기 단계에서 결함을 예방하고 품질을 보장하는 데 드는 비용이 훨씬 더 경제적이라고 본 것이다.
- 품질을 유지하는 데 드는 비용을 "결함을 예방하는 데 드는 비용" 으로 정의하며, 문제를 나중에 해결하려는 것보다 초기부터 품질을 관리하는 것이 장기적으로 훨씬 비용 효율적이라는 것을 강조했다.

정리하면, Crosby의 품질경영 4대 절대조건은 **품질의 정의, 예방의 중요성, 품질의 측정 방법, 품질을 위한 비용 관리**에 대한 철학을 담고 있다. 이를 통해 품질을 단순히 결함을 줄이는 것이 아니라, 고객의 요구를 충족시키기 위해 끊임없이 개선하는 과정으로 바라보는 접근 방식을 제시하고 있다. 이 4대 절대조건을 바탕으로 품질경영을 수행하면, 조직은 더 높은 품질 수준을 유지하면서도 효율적인 비용 관리가 가능하다.

## 신뢰성 관리

:::{.callout-tip icon=false title="기출"}
103-3-3
:::

**신뢰성**(reliability)은 부분품, 장치, 기기, 시스템이 주어진 어떤 조건 아래에서 의도했던 기능을 수행하는 확률, 즉 "고장나지 않을 확률"을 의미한다. 따라서 신뢰성은 시간 변화에 따른 동적인 품질이다. 신뢰성 평가척도로는 신뢰도, 평균고장간격, 평균고장시간 등이 있다.

**신뢰도**는 신뢰성에 대한 양적 표시로 임무기간 중 일어나는 단위시간당 고장회수로 나타내는 것이 일반적이며 이를 시간 함수로 볼 때 R(t)로 나타낸다. 이것은 제품이 t 시간 동안 고장이 나지 않는 확률이다. 즉, 제품을 사용하기 시작해서 어느 시점까지 전체 몇 %가 고장나지 않고 남아 있는가 하는 잔존률에 해당한다.

**신뢰성관리**는 성능과 신리ㅗ성, 보전성 그리고 가동성이 높은 제품을 경제적으로 제조하기 위해서 제품 개발로부터 설계, 제조, 사용 및 보전에 이르기까지 제품 전 생명 주기(life cycle)에 걸쳐 미리 설정된 신뢰성 계획에 따라 제품 신뢰성을 확보하고 유지하기 위한 종합적인 관리활동을 가리킨다.이를 위하여 신뢰성을 정량적으로 측정할 수 있는 척도를 설정하고 이를 바탕으로 불량원인을 발견하고고장 원인을 찾아내서 개선하여 가능한 그 영향을 줄이거나 제거시키고자 하는 활동이다.

품질경영적 관점에서 볼 때 신뢰성은 품질특성 중 하나이고 품질보증 기능을 한다. 따라서 신뢰성관리는 품질경영과 함께 상호 유기적인 관계에서 전개되어야 한다.

신뢰성은 고유신뢰성과 사용신뢰성으로 구분할 수 있다.

고유신뢰성
: - 제품 자체가 가지고 있는 고유한 신뢰성으로 제품 수명을 연장하고 고장을 적게 하는 신뢰성 설계나 공정관리, 공정해석에 의해 기술적 요인을 찾아내고 이를 시정하는 품질관리 활동으로 달성된다.
- 증대방안
        - 설계부문: 용장성 설계, 부하 경감, 안전계수, 환경조건 추정, 안저장치, 인간공학적 적합성 등
        - 제조부문: 자재, 기계, 제조방법, 작업관리, 품질관리 등

사용신뢰성
: - 제품이 만들어진 후 설계나 제조과정에서 형성된 제품 고유신뢰성이 유지 및 관리되도록 하는 신뢰성을 말한다.
- 증대방안
        - 사용부문: 사용방법, 교육훈련, 취급설명
        - 보전부문: 보전방법, 예비품 관리, 사용법, 안전요원 훈련
        - 환경부문: 저장, 운반, 포장, 사용 환경

고장 통계에 따른 신뢰성 비율은 다음과 같다.

```{mermaid}
flowchart LR
00[신뢰성]
01[고유신뢰성]
02[사용신뢰성]

11["부품, 재료에 의한 고장<br>30%"]
12["설계 기술에 의한 고장<br>40%"]
13["제조 기술에 의한 고장<br>10%"]

21["사용상 고장(운송,환경,조작,취급 등)<br>20%"]

00 --- 01 & 02
01 --- 11 & 12 & 13
02 --- 21
````

신뢰성 설계 3요소는 **고유 기술적 요소**, **소리 통계적 요소**, **관리 기술적 요소**이다.

고유 기술적 요소
: - 내 스트레스 설계
- 실용 설계
- 내 소음 설계
- **중복 설계**(redundancy)
- **fail safe 설계**
- **fool proof 설계**
- **derating설계**
- 안전 설계
- FMEA
- FTA
- 보전성 설계
- 신뢰성 시험
- 스크리닝
- 고장 해석 등

수리 통계적 요소
: - 신뢰도 예측
- 신뢰도 배분
- 신뢰성 발취 시험
- 데이터 해석
- 실험계획법
- 시뮬레이션
- 다구치 설계
- SQC 등

관리 기술적 요소
: - 설계심사(DR)
- Check List
- 표준화
- Trade off
- Configuration관리
- TQC
- QC 신 7가지 도구

## AQL

:::{.callout-tip icon=false title="기출"}
109-1-10
:::

**AQL**(Acceptable quality level)은 합격판정 샘플링검사에서 공정평균 품질수준으로 구매자가 만족할 수 있는 최대 불량률을 뜻하며, 흔히 합격품질지수라고 부른다. 이 때 로트 합격확률은 보통 95% 수준이다.

**AOQL**(Average outgoing quality limit)은 AOQ가 최대가 되는 출하품질을 뜻한다. 즉, 입고 제품 최대불량률(%)을 나타낸다.

AOL은 투입되는 원자재 품질, 로트가 합격할 확률, 포본 및 로트 크기에 따라 달라질 수 있다. 입고되는 원자재 품질이 아주 우수하면 출검 품질도 우수하나 원자재 품질이 불량하면 로트 전체가 기각되기에 불량 부품이 통과되지 않기 때문에 이 경우에도 출검 품질은 우수하게 된다. 입고되는 원자재 품질이 아주 좋지도 아주 나쁘지도 않으면 출검 품질이 더 나빠지고 출검 수준 불량률이 평균 출검품질한계라고 알려지 최대값에 근접하게 된다.

일반적으로 로트 크기를 N, 로트 불량률을 p라고 할 때, AOQ 값은 p값이 커짐에 따라 증가하게 되나 어느 수준을 지나게 되면 불합격될 가능성이 높아져 AOQ는 오히려 감소하게 된다.

## 품질비용

:::{.callout-tip icon=false title="기출"}
112-4-1
:::

**품질비용**(Quality Costs)은 제품이나 서비스 품질을 유지하거나 향상시키기 위해 발생하는 모든 비용을 의미한다. 품질비용은 보통 4가지 주요 카테고리로 분류되며, 각 카테고리에서 발생하는 비용은 다음과 같다.

예방비용 (Prevention Costs)
: - 예방비용은 품질 문제를 미리 방지하기 위한 활동에 드는 비용이다. 이는 품질을 향상시키고 결함을 사전에 제거하는 데 투입되는 자원이다.
        - 교육 및 훈련: 직원들에게 품질 관리 및 프로세스 개선에 대한 교육을 제공하는 비용
        - 품질 계획 및 설계: 품질 기준을 설정하고, 제품 개발 초기에 품질을 고려하여 설계하는 비용

평가비용 (Appraisal Costs)
: - 평가비용은 제품이나 서비스 품질을 측정하고 검사하는 과정에서 발생하는 비용이다. 품질을 확인하고 유지하기 위해 필요한 검사 및 테스트 비용이 포함된다.
        - 시험 및 검사: 제품이 생산된 후 품질을 검사하고 시험하는 데 드는 비용 (예: 생산라인에서의 품질 검사)
        - 감사 및 평가: 내부 품질 감사나 외부 인증 기관에 의한 품질 평가 비용

내부 실패비용 (Internal Failure Costs)
: - 내부 실패비용은 제품이 고객에게 전달되기 전에 발생하는 결함을 수정하는 데 드는 비용이다. 즉, 내부에서 품질 문제가 발견되어 이를 해결하기 위한 비용이다.
        - 불량품 재작업: 생산 과정 중 결함이 발견되어 제품을 수정하거나 재작업하는 데 드는 비용
        - 폐기 비용: 품질 기준에 미달한 불량품을 폐기하는 데 드는 비용

외부 실패비용 (External Failure Costs)
: - 외부 실패비용은 제품이나 서비스가 고객에게 전달된 후에 발생하는 품질 문제로 인한 비용이다. 고객 불만이나 반환, 리콜 등과 관련된 비용이 포함된다.
        - 리콜 비용: 품질 문제가 있는 제품을 시장에서 회수하는 데 드는 비용
        - 고객 불만 처리 및 보상: 품질 문제로 인해 고객에게 불만을 처리하고 보상하는 데 드는 비용 (예: 환불, 교환 등)

간단히 요약하면 다음과 같다.

요약
: - 예방비용: 품질 문제를 사전에 예방하기 위한 비용
- 평가비용: 품질을 측정하고 검사하는 데 드는 비용
- 내부 실패비용: 제품이 고객에게 전달되기 전 발생한 품질 문제 수정 비용
- 외부 실패비용: 제품이 고객에게 전달된 후 발생한 품질 문제 처리 비용

이 네 가지 품질비용 카테고리는 제품이나 서비스 품질 향상을 위해 적절한 관리와 투자로 문제를 최소화하는 데 중요한 역할을 한다.
