# 원가관리 {#sec-cost-management}

## PRM

:::{.callout-tip title="기출" icon=false}
106-1-8
:::

**PRM**(Pricing and Revenue Management)은 원가절감 활동으로 미국 영(M.S. Young)은 효과적으로 원가절감을 추진하기 위하여 6가지 원칙을 성실하게 준수해야 한다고 강조했다.

원가절감 6가지 원칙
: 1. 원가절감 계획 필요성을 명확히 한다.
1. 원가절감 분위기를 조성한다.
1. 원가절감 목표를 정확히 설정한다.
1. 원가절감 추진계획표를 작성한다.
1. 원가절감 성과를 평가한다.
1. 원가절감을 계속 진행한다.

원가절감을 위해서는 **변동비, 고정비** 의미를 이해 및 파악하고 이를 토대로 손익분기점, 의사결정기준점 등을 도출한 후 공급자와 구매자 힘을 가늠하여 전략을 수립한다.

## 감가상각

::: {.callout-tip icon=false title="기출"}
109-2-6
:::

감가상각이란 당해 자산에 대해경제적 효익이 발생하는 기간 동안 합리적이고 체계적인 방법으로 당해 수익에 대응시킬 비용을 인식하는 과정이다. 모든 유형자산은 보유기간 중 감가상각하는 것이 원칙이지만 토지와 건설중인 자산은 예외이다.

### 감가상각 계산 3요소

감가상각을 숫행하기위해서는 취득원가, 잔존가치, 내용연수를 알아야 하는데 이를 감가상각계산 3요소라고 한다.

취득원가
: > 유형자산 최초 구입가격 또는 제작가액에 이를 본래 목적에 사용가능하도록 하는데 소요된 일체 부대비용을 함계한 금액

잔존가치
: > 자산이 이미 오래되어 내용연수 종료시점에 도달하였다는 가정하에 자산 처분으로부터 현재 휙득할 금액에서 처분부대원가를 차감한 금액에 대한 추정치

내용연수
: > 기업에서 자산을 사용가능할 것으로 기대되는 기간 또는 자산에서 얻을 것으로 예상되는 생산량이나 이와 유사한 단위 수량

### 감가상각방법 종류

감가상각 방법에는 정액법, 정률법, 생산량 비례법, 이중체감잔액법, 연수합계법 등이 있다.

정액법
: - 내용연수에 걸쳐 매 기간 일정하게 감가상각비를 인식하는 방법
- 
$$
\text{당해연도 감가상각비 = } \frac{\text{취득원가 - 잔존가치}}{\text{내용연수}}
$$

정률법
: - 내용연수 동안 감가상각비가 매 기간 감소하는 방법으로 매 기간 자산 기초장부금액에 일정한 정률법을 곱하여 감가상각비를 계산
- 당기감가상각비 = 미상각 잔액(기초 장부가액) x 상각률
- $상각률 = 1-\sqrt[n]{\frac{잔존가액}{취득원가}}$, n은 내용연수, 미상각 잔액 = 취득원가 - 감가상각 누계액

생산량비례법
: - 보유중인 자산 가치감소가 단순히 시간이 경과함에 다라 나타나기보다는 생산량 또는 작업시간에 비례하여 나타난다는 전제로 계산
- 감가상각비 = (취득원가 - 잔존가치) x (실제생산량/총추정생산량)
- 생산 없이는 비용이 발생하지 않는다는 것을 전제하기 때문에 수익/미용 대응 관계를 잘 반영시켜 주는 방법
- 주로 광산, 유전, 산림 등과 같은 소모성 또는 고갈성 자산 채취산업에 많이 사용

이중체감잔액법
: - 미상각잔액에 매기 정액법에서 상각률에 2배를 곱하여 감가상각비를 계산하는 방법
- 미상각잔액에 일정한 상각률을 곱하여 삼가상각비를 구하게 되므로 시간이 경과하여 기초장부가액이 감소함에 따라 각 연도에 감가상각비도 점차적으로 감소
- 감가상각비 = (취득원가 - 기초감가상각누계액) x 상각률, 여기서 상각률 = (1/내용연수)x2

연수합계법
: - 정률법과 마찬가지로 초기에 많은 감가상각비를 인가하고 기간이 지나면서 적은 감가상각비를 인가하는 체감상각법 일종
- 급수법이라고도 하며, 취득원가에서 잔존가액을 차감한 금액을 내용연수 합계로 나누고, 그 금액에 내용연수 역순을 곱하여 산출
- 감가상각비 = (취득원가 - 잔존가액) x (내용연수 역순/내용연수 합계)
