# 경영과학(OR) {#sec-or}

## 분석적 계층화 과정 (AHP)

#97-1-3 

**분석적 계층화 과정**(AHP, Analytic Hierarchy Process)는 Thomas L. Saaty 교수가 1970년대 창안한 다기준 의사결정방법론이다.[^6-4-1-AHP]

[^6-4-1-AHP]: https://ko.wikipedia.org/wiki/분석적_계층화_과정  

### AHP 원리

인간이 의사결정 시 두뇌가 단계적 또는 위계적 분석 과정을 활용한다는 사실에 착안하여 개발되었다. 연구 결과에 따릅면 사람은 문제를 해결할 대 다음 세가지 원칙을 따른다.

1. 계층적(hierarchy) 구조 설정
2. 상대적 중요도(weight) 설정
3. 논리적 일관성 (logical consistency) 유지

계층적 구조 설정
> 인간은 복작한 현상을 그 구성요소 별로 나아가 더 작은 부분으로 나누어 종국적으로 계층 구조를 설정한다. 가장 기본적으로 맨 윗부분은 목적(goal)을 두고, 그 밑에 판단기준이 되는 기준(criteria)을, 그리고 가장 아래 계층에 대안(alternatives)을 두는 구조이다. 판단기준은 분석 대상에 따라 하위 계층을 두어 복잡한 구조를 가질 수도 있다.

상대적 중요도 설정
> 인간은 관측한 사물 사이의 관계를 인식하고 유사한 사물들을 짝으로 묶어 특정 기준에 대하여 비교하고 그 짝의 구성 인자 사이의 선호도를 판단하는 능력을 소유하고 있다. 최종적으로 상상이나 논니적 과정을 통하여 그들이 내린 판단을 종합하여 전체 시스템에 대한 이래를 보다 강화한다. AHP 특징은 많은 의사결정 요소 간 가중치 또는 중요도(weight)를 간단한 쌍대비교(1:1)를 통해 산출해 내는데 있다.

논리적 일관성 유지
> 인간은 사물이나 생각을 논리적 일관성을 갖도록 관계를 설정하는 능력을 갖고 있다. 일관성은 두 가지 이미를 갖는데 유사한 사물이나 생각을 동질성이나 관련성에 따라 묶는 것과 특정한 기준이 있을 경우 생각이나 사물 간 강약을 기준에 따라 논리적인 방법으로 구성한다는 것이다.

### 4가지 공리

기본적인 4가지 공리는 다음과 같다.

상호비교(reciprocal comparison)
> 의사결정자의 두 대상에 대한 상호 비교가 반드시 가능해야 하며 중요성 정도를 나타낼 수 있어야 한다. 이 중요성 정도는 반드시 역조건을 성립시켜야 한다. 즉 A가 B보다 x배 중요하다면 B는 A보다 (1/x)배 중요시되어야 한다.  

동질성(homogeneity)  
> 중요성 정도는 한정된 범위 내 정해진 척도를 통해 표현되어야 한다. 즉 비교대상 간 비교 가능한 일정한 범위를 갖는 기준들이 존재해야 한다.  

독립성(independence)  
> 상대적 중요도를 평가하는 동일 수준 요인들은 특성이나 내용 측면에서 서로 관련성이 없어야 한다.  

기대성(expectation)  
> 계층구조는 의사결정에 필요한 모든 사항들을 완전하게 포함하는 것을 가정한다. 즉 위사결정자의 합리적 기대에 부합하는 완전한 계측구조를 갖고 있어야 한다. 반면 수준 수가 많아 계층 구조가 깊으면 계산상 복잡성을 유발시키므로 일반적으로 3-7 수준으로 계층을 형성한다.  

각 공리는 이론적 또는 실제 이용 측면에서 타당성을 가지기 위해 필요하다. 그 근거는 다음과 같다.

**상호비교** 위배는 모호한 질문 때문에 의사결장가 질문을 이해하지 못하는 경우 발생한다. 판단이나 상대비교를 이끌어 내는데 사용되는 질문이 명백하지 않거나 질문이 올바르게 언급되지 않았다면 쌍대비교가 성립될 수 없다는 것을 의미한다.

**동질성**을 만족하지 못한다면 비교되는 요소는 동일하지 못하게 되어 쌍대비교가 성립할 수 없다. 즉, 동질성이란 비교 대상들이 비교 가능하다는 것을 의미한다.

**독립성**은 판단 기준 가중치가 고려되는 대안들과 독립적이어야 한다는 의미이다. 특정 대안 선택에 유리한 가중치 산출을 피애야 하며 두 기준을 쌍대비교할 때 상위 수준 요소만을 고려해야 한다.

**기대성**을 만족하지 못한다면 의사결정자는 자신의 합리적 기대를 맞추는 데 필요한 모든 대안이나 모든 판단기준을 사용하지 않는 것이다. 즉, 의사결정이 불완전하게 이루어져 기대를 반영하지 못하게 된다.

### 분석 과정

AHP 분석은 다음과 같은 가정을 따른다.

1. 문제설정 및 계층적 구조화
2. 문제별 쌍대비교 단계
3. 가중치 산정 및 일치성 분석

```{mermaid}
flowchart TB
subgraph 목표
0[스마트폰 구입]
end
subgraph 평가기준
11[디자인]
12[가격]
13[성능]
14[서비스]
end
subgraph 대안
21[삼성]
22[샤오미]
23[애플]
end
0 --- 11 & 12 & 13 & 14
11 --- 21 & 22 & 23
12 --- 21 & 22 & 23
13 --- 21 & 22 & 23
14 --- 21 & 22 & 23
```

문제설정 및 계층적 구조화
> 스마프폰 구입을 위해 디자인, 가격, 성능, 서비스를 판가기준으로 3개 제품을 중 선택하고자 한다.

문제별 쌍대비교
>

가중치 산정 및 일치성 분석
>



## 분석 네트워크 프로세스 (ANP)

**분석 네트워크 프로세스**(ANP, Analytic Network Process)는 AHP 분석 한계로 인해 1996년 Saaty 교수가 기존 AHP 기법을 보완하여 개발되었다. AHP는 구성요소간 독립성을 가정하였지만 현실에서는 수평적 상호관계, 수직적 종속관계가 존재하기 때문에 단순한 계층적 구조만으로 설명할 수 없는 경우가 있다. ANP는 AHP 기법에 기초를 둔 시스템으로 요소간 비선형 관계를 모델화하는 복작한 의사결정을 다룰 수 있다. 

구분|AHP|ANP
-|-|-
구조| 트리 구조| 네트워크 구조
가정| 각 구성 요소 간 상호 독립| 각 구성 요소 간 상관관계 존재
특징| 단방향 흐름, 계산이 비교적 단순| 상호 종속성, 피드백 효과, 계산이 복작하여 시간 과다 소요

  



