# 정보화활용기술(스마트팩토리 등) {#sec-ict}

## 정보화 활용기술

::: {.callout-tip icon=false title="기출"}
109-2-1
:::

@sec-scm (Supply chain management)
: - 공급망 관리를 의미하며, 이는 제품 생산을 위한 프로세스를 효율적으로 관리하고, 수요 예측을 통한 재고 관리 등을 포함한다. SCM은 원자재 구매부터 최종 제품 배송까지 모든 과정을 최적화하여 기업 경쟁력을 높이는데 중요한 역할을 한다.

@sec-crm (Customer relationship management)
: - 고객 관계 관리를 의미하며, 이는 기업이 고객을 중심으로 비즈니스를 수행하기 위한 방법론으로 고객 정보를 수집하고 분석하여 개인화된 서비스를 제공하고 고객 만족도를 높이며 장기적인 관계를 유지하는 것을 목표로 한다. CRM은 이러한 활동을 지원하는 IT 시스템으로 마케팅, 판매, 서비스 등 여러 부서가 함께 사용할 수 있도록 설계되었다.

ERP (Enterprise Resource Planning)
: - 전사적 자원 관리를 의미하며, 이는 기업 내 생산, 재무, 회계, 영업, 구매, 재고 등 전반적인 비즈니스 프로세스를 시스템 하나에서 통합적으로 관리할 수 있게 해 주는 소프트웨어를 말한다. ERP 시스템을 사용하면 데이터 일관성과 정확성이 향상되며, 업무 프로세스 간소화와 생산성 향상을 기대할 수 있다. 대표적인 ERP 솔루션으로는 SAP, Oracle 등이 있다.

KMS (Knowledge management system)
: - 지식관리시스템으로 조직 내 지식, 정보, 경험 등을 체계적으로 수집, 정리, 공유함으로써 조직 효율성을 높이고자 하는 시스템이다. 이 시스템은 직원들이 필요한 정보를 쉽게 찾을 수 있도록 돕고, 중복된 작업을 줄여주며, 새로운 아이디어나 솔루션을 빠르게 공유할 수 있게 한다. 또한 기존 지식을 재활용하거나 새롭게 조합해 새로운 가치를 창출하는 데도 기여한다. 대표적인 지식 관리 시스템에는 위키, 블로그, 포럼, 소셜 네트워크 플랫폼 등이 있다.


## 스마트팩토리 기술

### CPS 

:::{.callout-tip icon=false title="기출"}
112-1-5
:::

**CPS**(Cyber-Physical System)는 물리적 시스템과 컴퓨터 시스템이 상호작용하며 실시간으로 데이터를 처리하고 제어하는 시스템을 의미한다. 이러한 시스템은 센서, 액추에이터, 제어 시스템, 컴퓨터 네트워크 등을 포함하여, 물리적 세계와 디지털 세계가 긴밀하게 결합된 구조를 가진다.

주요 특징
: - 물리적 시스템과 디지털 시스템의 통합: CPS는 물리적 장치와 이를 제어하는 컴퓨터 시스템을 결합하여, 현실 세계에서 발생하는 데이터를 실시간으로 처리하고 반응함
- 실시간 처리: CPS는 실시간으로 데이터를 수집하고 분석하여, 물리적 환경에 즉시 반응함
- 상호작용: CPS는 센서와 액추에이터를 통해 물리적 환경을 감지하고 제어하며, 이 과정에서 컴퓨터 시스템이 중요한 역할을 함
- 네트워크 연결: CPS는 인터넷을 통한 상호 연결을 통해 다양한 장치들과 정보를 주고받으며 협력함

적용 예시
: - 스마트 홈 시스템: 집안의 온도, 조명, 보안 시스템 등을 실시간으로 제어하고 모니터링함
- 자율 주행 차량: 자동차가 센서와 컴퓨터 시스템을 통해 도로 상황을 인식하고, 안전하게 운전 결정을 내림
- 산업 자동화 시스템: 제조 공정에서 센서와 로봇을 이용해 생산 과정과 품질을 실시간으로 관리함

```{r}
#| echo: false
# #| tbl-colwidths: [10,90]

options(knitr.kable.NA = '')

tb <- data.frame(
  장점 = c("**효율성 향상**: 실시간으로 데이터를 처리하고 제어하여 시스템의 전체적인 효율성을 높임.",
           "**자동화**: 사람의 개입 없이 자동으로 작업을 수행함으로써 반복적인 작업을 줄이고, 인적 오류를 최소화함.",
           "**안전성 증대**: 센서와 제어 시스템이 상호작용하여 잠재적 위험을 실시간으로 감지하고 대응함."),
  단점 = c("**시스템의 복잡성**: 다양한 구성 요소와 상호작용으로 인해 시스템 설계와 유지 관리가 복잡함.",
           "**보안 문제**: 네트워크 연결로 인해 해킹, 데이터 유출 등의 보안 위협에 취약할 수 있음.",
           "**높은 비용**: 고도의 기술적 요구와 장비가 필요하여 초기 구축 비용이 매우 높을 수 있음.")
)

knitr::kable(tb)
```

### AR {#sec-ar}

:::{.callout-tip icon=false title="기출"}
115-1-1
:::

**증강현실**(Augmented Reality, AR)은 현실 세계에 가상 정보를 실시간으로 덧붙여서 보여주는 기술이다. 즉, 사용자에게 실제 환경과 가상 환경을 동시에 경험하게 하는 기술로, 현실과 가상 요소가 실시간으로 결합되어 새로운 형태로 경험이 제공된다.

증강현실의 주요 특징
: - **실시간 상호작용**: 사용자와 환경 간의 실시간 상호작용을 지원한다. 예를 들어, 사용자가 스마트폰을 이용해 카메라로 현실을 비추면, 그 화면에 가상 객체가 실시간으로 겹쳐 보여진다.
- **현실과 가상 정보 결합**: 현실 세계에 가상 객체나 정보를 덧붙여서 제공하므로, 사용자는 실제 환경을 바탕으로 추가된 정보를 확인할 수 있다.
- **위치 기반 서비스**: GPS나 센서를 활용해 사용자의 위치를 파악하고, 그 위치에 맞는 가상 정보를 제공하는 것이 가능하다. 예를 들어, 특정 장소에서만 나타나는 가상 객체를 보여주는 방식이다.

증강현실의 구성 요소
: - **하드웨어**: AR 기술을 구현하기 위한 장치로, 스마트폰, 태블릿, AR 안경(예: Microsoft HoloLens, Magic Leap) 등이 있다.
- **소프트웨어**: AR 환경을 구현하는 앱이나 프로그램으로, 현실 세계 영상과 가상 객체를 실시간으로 결합하고 이를 표시하는 소프트웨어가 필요하다. 예를 들어, ARKit(애플), ARCore(구글) 등이 있다.
- **인터페이스**: 사용자와 가상 객체 간 상호작용을 가능하게 하는 시스템으로, 화면 터치, 음성 인식, 제스처 인식 등이 포함된다.

증강현실의 적용 분야
: - 게임: 포켓몬 GO와 같은 게임은 증강현실 기술을 활용하여, 현실 세계에서 가상 캐릭터를 찾아내고 상호작용할 수 있도록 한다.
- 교육: AR을 활용한 학습은 학습자가 현실 세계와 가상 정보를 동시에 경험하면서 보다 직관적이고 몰입감 있는 학습을 할 수 있게 해준다. 예를 들어, 해부학 수업에서 AR로 인체 3D 모델을 실시간으로 보는 방식이다.
- 의료: 의사들이 AR을 이용해 환자의 신체 상태를 실시간으로 확인하거나 수술 중에 중요한 정보를 가상 화면으로 제공받을 수 있다.
- 상업 및 쇼핑: 가상으로 제품을 미리 보고 구매할 수 있도록 돕는 AR 기술이 쇼핑몰이나 온라인 쇼핑에서 점점 더 많이 사용되고 있다. 예를 들어, 가구를 구매하기 전에 집에 어떻게 배치될지 AR로 미리 확인할 수 있다.
- 관광 및 내비게이션: AR을 활용한 관광 안내 시스템은 현실 세계에 가상 관광 정보나 경로를 덧붙여 여행객이 더욱 쉽게 목적지를 찾을 수 있도록 도와준다.

증강현실의 장점
: - 직관적이고 몰입감 있는 경험을 제공하여 사용자가 더욱 쉽게 정보를 이해하고, 상호작용할 수 있도록 한다.
- 현실 세계와 가상 정보를 실시간으로 결합함으로써, 다양한 산업에서 실용적인 활용이 가능하다.
- 위치 기반 서비스나 맞춤형 정보 제공이 가능하여, 개인화된 경험을 제공할 수 있다.

증강현실의 한계
: - 기술적 한계: 현재 AR 기술은 하드웨어나 소프트웨어 성능에 따라 경험하는 질이 달라지며, 완벽한 현실과 가상 정보 결합은 아직 기술적으로 도전적인 과제가 될 수 있다.
- 비용 문제: AR을 구현하기 위한 장치나 소프트웨어가 고가일 수 있으며, 이는 상용화와 대중화에 장애물이 될 수 있습니다.
- 지속적인 개발 필요: AR 기술은 계속해서 발전하고 있지만, 아직 많은 분야에서 적용이 제한적이다.

증강현실은 실제 환경에 가상 정보를 덧붙여 새로운 경험을 제공하는 혁신적인 기술이다. 다양한 산업에서 유용하게 활용될 수 있으며, 앞으로 더욱 발전하면서 우리 일상 뿐만아니라  생산 현장에도 많은 변화를 가져올 것으로 기대된다.

## 공장자동화

::: {.callout-tip icon=false title="기출"}
109-3-3
:::

**자동화**(Automation)는 생산을 운영하고 통제하기 위해 기계, 전자, 컴퓨터 시스템의 응용과 관련된 일체 기술을 말한다.

협의의 개념
: > 컴퓨터와 각종 공작기계, 계측장비 등을 이용하여공장 생산을 자동화한 시스템

광의의 개념
: > 수주에서 설계, 제조, 검사 및 출하에 이르는 일체 생산 활동을 효율적, 유기적으로 결합시키는 시스템 기술

일반적으로 기계화와 자동화는 인간이 수행하는 직무를 기계 또는 전자기기를 사용하여 운영하는 것이다. 기계화와 자동화는 서로 구별 없이 자주 사용되기도 한다. 기계화에 비해 자동화는 피드백(feedback) 기능을 가지고 있다. 피드백 기능이란 변동이 발생할 때, 자동적으로 기계가 원래 상태로 환원할 수 있는 능력을 말한다.

자동화 배경
: 1. 환경, 안전 법규
1. 생산노동력 감소, 3D 업종 인력 부족
1. 단납기 신속 대응, 고객 요구 납기 만족 - 기업 경쟁력 심화 및 소비자 욕구 다양화
1. 기계 가동률 향상, 생산성 향상
1. 안정된 품질 확보 - 높은 정확도를 요구하는 경우
1. 노사 이해 대립
1. 생산 시스템 거대화 - 원재료, 에너지 비용 상승
1. 재공품 재고 축소

자동화 필요성
: 1. 저성장 고착화로 비용 절감 요구
1. 변동성(고객 Needs 등)증가로 제품 수명주기 단축 - 맞춤형 대량생산 필요
1. 안전, 노동력 부족, 높은 노무비 - 숙련노동인력 부족과 인적자원 고령화
1. 생산성 향상, 품질 향상, 생산 리드타임 감소
1. 원자재 효율적 사용
1. 재공품 재고 감소

자동화 목적
: 1. 작업환경 개선 및 인력자원 부족 해결
1. 제품 품질 균질화를 통한 소비자 신뢰 확보
1. 생산효율 향상(생산시간 단축 -> 생산성 향상 -> 품질향상 -> 재공품 감소)을 통한 이익 극대화
1. 생산 시스템 효율적 운영 - 공장, 설비 간 정보 흐름 원활화 추구
1. 원가절감을 통한 제품 가격 인하
1. 다양한 제품, 유연한 납기 대응력

추진방향
: - 데이터 기반 의사결정이 실시간 이행과 총체적인 관점에서 최적화
- 제조와 ICT 융합으로 인간과 로봇이 공유하여 무결점 제품 생산

5대 요소
: 1. 감지기
1. 제어신호 처리장치
1. 액추에이터
1. 소프트웨어 기술
1. 네트워크 기술

자동화 대상
: - 생산관리 - 공정관리, 품질관리, 자재관리, 원가관리, 노무관리
- 반복작업 - 가공물 운반, 자재 반입 및 반출 등
- 숙련 작업 - 용접 작업, 각종 자동장치 및 조립 작업 등

자동화 장점
: 1. 생산성 증가 -> 가동률 향상 사이클 타임을 줄인다.
1. 작업조건 향상, 작업 편의성 및 위험요소 제거 - 육체적 부담, 위험요소, 불가능한 작업
1. 생산제품 일관성 향상(균일화, 표준화) -> 제품 불량률 저감
1. 직접적인 인간 노동력 및 비용 감소
1. 생산설비 수명연장 및 생산원가 절감

자동화 단점
: 1. 합리화 초기 수단 시 초기 설비 투자비가 많이 들어가며 중복투자 우려
1. 소비자 욕구가 다양해지면서 제품 수명이 짧아져 생산 환경 변화에 따른 유연성 문제 대두
1. 시스템 구축 방법에 따라 운영 유지비 소요 -> 자동화하기 전보다 설계, 설치, 운영, 유지, 보수에 높은 기술 수준이 필요하며 운영, 유지, 보수를 담당할 고급 기술자 양성 필요
1. 보안에 취약해 위협을 받기 쉽다
1. 성인화, 무인화 유도를 못할 경우 인력 증가 우려
1. 제품 품질 산포 불안정 시 설비의 잦은 정지 및 가동률이 저하됨
1. 일관화 미 고려 시 라인 밸런싱 로스가 발생되고 재공 재고도 증가됨

### 자동화 유형

고정형 자동화(Fixed automation)
: - 성숙기 제품에 대해 표준화된 대량 생산 (소품종/저원가/대량생산)
- 노무비 절감, 생산 소요시간 단축
- 전용설비, 대형화로 초기 투자금액이 큼
- 공정 경로 및 조립 순서가 고정, 단순 반복작업 수행
- 가공(조립) 작업 순서가 설비 배치에 의해 고정
- 복잡한 많은 동작이 한 가지 설비로 통합, 조정

프로그램 자동화(Programmable automation)
: - 프로그램 지시에 의해 다양한 작업을 수행(산업로봇, NC 공작기계)
- 다양한 제품, 배치 소량 생산
- 작업순서 변경 가능한 성능 보유한 생산설비

유연형 자동화(Flexible automation)
: - 다품종소량 생산 목적
- 프로그램 가능 자동화보다 더 맞춤화된 장비 사용, 장비 준비, 교체 시간이 짧아 제품을 여러 조합으로 생산
- 범용설비, 소규모 투자
- 단속 공정 장점인 탄력성과 라인 공정의 높은 생산성(CIM, FMS)등
- 기종 변경 시 대기시간없이 다양한 제품 생산 가능
- 시스템이 재프로그램밍되고 물리적 설정 변경에 다른 생산시간 낭비가 없음

구분 | 고정형 자동화 시스템 | 유연형 자동화 시스템
-|-|-
설비 투자 규모 | 매우 큼 | 비교적 적은 편이지만, 기계화된 시스템에 비해선 큰 편임
생산품목 | 소품종 대량 생산에 적합 | 다품종 소량생산 가능
공정 유연성 | 가공 순서, 생산품목 변경 시 많은 비용 소요 | 프로그램에 의해 통제가 가능하며 생산조직의 유연성이 높음
생산 속도 | 단위 시간당 높은 생산량 | 상대적으로 낮음
적용 사례 | 자동 가공라인, 조립라인 | NC 기계, 로봇, CAD/CAM

### 자동화 변천

LCA | FA | FMS | CIM | Smart Factory
-|-|-|-|-
간이 자동화 | 공장 자동화 | 유연생산시스템(생산 방식에 의한 자동화) | 컴퓨터 통합생산 시스템(공장자동화 + 정보 자동화) | 스마트 팩토리 (ICT 기반 자동화 공장)
생산에 필요한 각종 생산설비를 보다 싸고, 보다 빠르게 제작 활용하는 것 | 수주에서 출하에 이르는 활동에 대해 적용 | 각종 자동화기기, 로봇, CAD/CAM, 자동창고 등 다양한 설비나 소프트웨어를 이용하여 유연한 생산체계를 구축한 시스템 | 설비 자동화와 생성된 생산 데이터의 정보화를 통합(자동화 - 설비, 창고 등, 정보화 - 계획, 운영 및 통제 데이터, MRP, MRP II, 표준 데이터 등), 다품종 소량생산 체제에 유연하게 대응 가능 | ICT와 기계 산업 융합을 통해 제조업 완전 자동 생산 체계를 구축하고모든 공정이 최적화되는 생산 현장

스마트 팩토리와 자동화 차이점은 다음과 같다.

구분 | 내용 | 생산체제
-|-|-
공장 자동화 | - 1세대 자동화: 전용 기기로 사용<br> - 2세대 자동화: 전용 기기 공정 중간에 로봇 연결, 전용 기기와 로봇이 각각 구동하여 작업자가 투입되어 함게 작업 및 전체를 관리<br> - 산업용 로봇을 전용 기기처럼 사용 | 대량생산 체제
스마트 팩토리 | - 3세대 로봇화 추구: 로봇 중심 자동화 추구<br> - 로봇을 사람이 하는 공정을 대체(협동 로봇)<br> - 다양한 센서 활용, PC 환경과 동일한 인터페이스 환경 구축으로 연결성, 유연성, 지능성 확보 | 고객 맞춤형, 다품종소량 생산

### 자동화 도입 시 유의사항

- 생산 전략은 기업 전략과 일관성유지
- 생산 관련 의사결정은 기업 전체 입장에서 경쟁력 제고 방향으로
- 도입 시스템에 대한 관리능력 보유
- 자동화 투자 여부 결정 시 비용 절감 외 시장 적응성, 고객 서비스 등에 대한 평가 중시


궁ㄹㄴㅁㄹ
