# 서비스운영관리 {#sec-service-operation}

## 마케팅 믹스 4P

:::{.callout-tip}
## 기출

#97-1-11
:::

```{mermaid}
flowchart TB
0["마케팅 믹스 4P"]
11["제품(Product)"]
12["유통(Place)"]
13["가격(Price)"]
14["판매촉진(Promotion)"]

0 --- 11 & 12 & 13 & 14
```

제품(Production)
: - 유형 물건 뿐만 아니라 기업에서 제공하고 고객이 이용하는 무형 서비스까지 포함하는 넓은 의미

유통(Place)
: - 제품을 판매하고 소비자가 구매할 수 있는 경로 의미

가격(Price)
: - 소비자가 기업이 제공하는 제품 또는 서비스를 구매할 때 지불하게 되는 비용을 의미

판매촉진(Promotion)
: - 광고 외 PR, 이벤트, 할인 ㄹ행사, 인적 판매, SNS 홍보, DM 등 자사 상품을 알리고 판매를 촉진하기 위한 모든 활동을 아우르는 개념

## 서비스 접접

:::{.callout-tip title="기출" icon=false}
103-1-13
:::

**서비스 접점**(서비스 인카운터, service encounter)은 스칸디나비아 항공사 사장인 얀 칼슨(Jan Carzon)이 주창한 개념으로 고객과 한 기업 서비스가 만나는 순간을 지칭한다. 즉 기업이 서비스를 제공할 때 고객과 직접 만나는 접점으로 고객은 이 순간을 통해 서비스를 구매할 것인지를 판단하게 된다. 때문에 서비스 인가운터는 흔히 '진실의 순간'(MOT, moment of truth)이라는 별칭으로 불리우기도 한다. Schmenner(1995)는 서비스 인카운터가 곧 서비스 기업 경쟁력을 결정짓는 척도로 규정하였고, 이를 구성하는 세가지 요소를 **서비스 과업(service task)**, **서비스 제공 시스템(service delivery system)**, 그리고 **서비스 표준(service standard)**을 지적한 바 있다. Fitzsimmons & Fitzsimons(1995)는 서비스 조직, 종업원, 고객 상호작용이라는 세 개 요소로 서비스 인카운터를 파악했다. 

서비스 제공자 (Service Provider)
: - 서비스 제공자는 고객과 직접적으로 상호작용하는 직원이나 시스템을 말한다. 고객의 요청을 처리하고, 서비스 품질을 전달하며, 고객의 경험을 형성하는 중요한 역할을 한다. 서비스 제공자의 태도, 전문성, 친절도 등은 고객의 경험에 큰 영향을 미친다.

고객 (Customer)
: - 고객은 서비스 인카운터에서 서비스 제공을 받는 사람이다. 고객은 그들의 기대와 요구사항을 가지고 서비스 제공자와 상호작용하며, 그 경험이 만족스러웠는지 아니면 불만족스러웠는지 평가한다. 고객의 행동과 반응은 서비스 인카운터의 성패를 가늠하는 중요한 지표가 된다.

서비스 환경 (Service Environment)
:- 서비스 환경은 고객과 서비스 제공자가 상호작용하는 물리적, 사회적, 또는 디지털 환경을 의미한다. 이 환경은 매장, 웹사이트, 앱, 콜센터 등 다양한 형태일 수 있으며, 공간의 디자인, 분위기, 편의성 등이 고객의 서비스 경험에 영향을 미친다. 좋은 서비스 환경은 고객이 편안하고 긍정적인 경험을 느낄 수 있도록 도와준다.

:::{.callout-note title="MOT" icon=false}

**MOT**(moment of truth)는 서비스 현장에서 고객이 서비스 기업을 만나는 모든 순간을 의미한다. MOT는 투우 경기에서 유래된 용어로 투우사와 소가 대결하는 투우 경기에서 투우사가 소 급소를 찌르는 마지막 순간을 의미한다. 그래서 MOT는 '피하려고 해도 피할 수 없는 순간', '실패가 허용되지 않는 순간'을 의미한다.

:::
