# 생산혁신기술 {#sec-production-innovation}

## 칸판 생산방식

#97-1-5

칸판(Kanban, 또는 간판으로 읽음)생산 방식은 "필요한 것은 필요한 때에 필요한 만큼만"이라는 JIT(Just In Time) 사상을 실현하기 위해 도요타에서 창안 되었다. JIT 생산에 있어 정보 시스템 역할을 한다. 즉 어떤 제품이나 부품이 언제 얼마나 필요한가를 알려주는 기능이다.

### 칸판 역할

칸판은 엽서 크기의 카드나 전표로 작업 지시표 내지 이동표 역할을 한다.

1. 생산, 운방 지시 정보
    - 무엇을 얼마 만큼 생산해서어디로 운반하는가?
    - 어떤 자재를 어디로부터 얼마 만큼 조달하도록 하는가?
2. 눈으로 보는 관리 도구
    - 과인생산 제어, 최소 자재량에 대한 통제, 진척 상황 판단
3. 개선 도구
    - 과잉 공급된 자재나 평준화 생산 흐름 상황을 파악

### 칸판 종류

칸판 종류는 다음과 같다.

생산지시 칸판
: - 작업지시표 역할, 생산부문에 대한 생산지시용

인수(이동) 칸판
: - 현품표와 이동표 기능으로 뒷 공정이 앞공정으로부터 물품을 인수할 때 사용

임시 칸판
: - 임시 생산 경우에 사용

전자 칸판
: - 운반 기간이 3~4일 이상 걸리는 경우

기타
: - 칸판 역할을 수향할 수 있는 신호
    - 용기 시스템: 전용 용기를 칸판으로 사용
    - 무용기 시스템: 맥도널드 주문 접수원 금전 등록기에 입력한 정보가 주방으로 전달(칸판 역할)

### 칸판 용기 수 산정

<font color="orange">업데이트 예정</font>

### 칸판 운영 규칙

칸판 운영 규칙은 다음과 같다.

- 모든 컨테이너 부품에 칸판을 부착한다.
- 뒷 공정에서 앞공정으로 가지러 간다(필요 시 필요한 양만 생산하고 인수해 가도록 함).
- 앞 공정은 뒷 공정에서 가져간 만큼만 생산한다(공정품 재고를 최소로 하기 위함).
- 불량품을 뒷 공정에 보내지 않는다(불량으로 인한 솔실을 막고 칸판 흐름 보증).
- 생산을 평준화 한다.
- 칸판은 세부적인 조정이 가능하다(수요 변화 내지 생산현장 사정에 적응하는 능력 갖춤).
- 공정을 안정화하고 합리화 한다(생산 안정성 유지와 낭비 제거).

### 칸반 운영 조건
칸반방식을 운영하기 위한 조건은 다음과 같다.

- 자동화와 생산평준화
- 소로트화
- U자형 설비배치와 다기능공 육성
- 작업 표준화

칸반 방식
::: {.callout-warning icon="false" title="칸판 방식 적용이 어려운 이융"}
1. 원칙을 준수하며 속도 있게 진행하기 어려움
2. 거듭되는 시행착오에 의한 좌절, 피로감
3. 당장 혼란과 손해를 두려워함
4. 칸판 방식 적용을 기법적인 측면에서만 접근 (종업원 인식 부족)
5. 기법 적용과 접근 방법 오류
6. 지속적인 관리 부재

```
