## 용어 {#sec-terms .unnumbered}

:::{.callout-tip icon=false title="기출"}
97-1-9
:::

::: {#def-투입시간}
## 투입시간(부하시간)
- 조업시간에 회사가 규정하는 법정 휴지시간을 제외하고설비가 실제 가동하도록 정의된 시간
:::

::: {#def-가동시간}
## 가동시간
- 부하시간에서 정지시간을 제외한 시간으로 설비가 제조(작업)활동을 위해 실제 가동한 시간
- 가동시간 = 부하시간 - 정미시간
:::

::: {#def-정미가동시간}
## 정미가동시간
- 설비가 주어진 기능과 성능을 발휘하여 제품 생산에 기여한 시간
- 정미가동시간 = 가동시간 - 순간정지시간 = 완성수량 x 실제 사이클 타입
:::

::: {#def-표준생산공수}
## 표준생산(량) 공수
- 제품 1개를 만들기 위한 표준작업시간과 생산량을 곱하여 계산되는 것으로, 정해진 방법과 작업 속도로 작업했는지를 판단하는 공수
- $\sum(표준작업시간 \times 생산량)$
:::
::: {#def-사이클타임}
## 사이클 타임 (Cycle time)
- 제품이나 부품 1단위가 공정에서 작업을 시작해서 완료되기까지 연속 경과된 사간을 의미하며, 제품이나 부품 등이 가공되는 대상물 관점에서 보는 시간
:::

::: {#def-피치타임}
## 피치 타임 (Pitch time)
- 최종 공정으로부터 완성품이 되어 나오는 시간적 간격, 즉, 1일 생산목표량을 달성하기 위한 제품 단위당 소요 제작 시간
:::

::: {#def-리드타임}
## 리드 타임 ( Lead time)
- 재료 입고에서부터 완성품 출하(납품)에 이르기까지 시간
- 설계/개발 리드 타임, 부품 조달 리드 타임, 생산 리드 타임, 출하 리드 타임

::: {#def-정미시간}
## 정미시간
- 대상작업의 기본적 내용으로 규칙적, 주기적으로 반복되는 작업 부분의 시간으로, 순수하게 작업에만 사용된 시간
:::

::: {#def-여유시간}
## 여유시간
- 대상작업의 필요한 내용으로 불규칙적, 우발적으로 발생하는 시간
:::

::: {#def-표준시간}
## 표준시간
- 적당한(부과된 작업량을 올바르게 수행) 숙련도를 지닌 작업자가 주어진 작업 조건 하에서 보통 작업 속도와 정상적인 피로와 지연을 수반하면서 규정된 질과 양의 작업을 규정된 방법에 따라 1단위 수행하는데 소요되는 시간
:::

:::{.callout-tip title="기출"}
97-1-13
:::

::: {#def-부가원가}
## 부가원가
- 원가이나 비용이 아닌 항목으로 기업주 보수, 자기자본 이자, 기업주 소유 토지계산 지대 등이 해당하며 원가계산상으로 원가로 취급, 손익계산상 비용으로 취급하지 않음
:::

:::{#def-중성비용}
## 중성비용
- 손익계산상으로 비용이나 원가로 취급하지 않는 항목으로 기부금, 유가증권평가손실 등과 같이 생산에 직접 관계가 없는 비용
:::

:::{.callout-tip title="기출"}
100-1-1
:::

::: {#def-RoHS}
## RoHS
- **RoHS**(Restriction of the use Hazardous Substance in EEE)는 전기 및 전자제품을 제조함에 있어 특정 유해물질 사용을 제한하는 규정으로, 유럽연합에서 발효한 환경규제이다. 규정한 유해물질로는 납(Pb), 카드뮬(Cd), 수은(Hg), 6가크롬($Cr^{6+}$), PBBs(Ploybrominated Phenyls), PBDEs(Ploybrominated Diphenyl Ethers)이다. 유럽 내 생산 및 수입되는 모든 제품에 대해 WEEE(EU 전자제품 페기물 지침)로 인한 인체와 환견에 대한 위험을 감소시키기 위한 규정으로 2006년 7월부터 시행하고 있다.
:::

:::{.callout-tip title="기출"}
100-1-6
:::

::: {#def-DEA}
## DEA
- **DEA**(Data Envelopment Analysis)는 1978년 Charnes, Cooper, Rhodes에 의해 처음으로 제안되었으며, OR/M(Operations Research/Management, 운영과학/경영)에서 가장 널리 활용되는 방법 중 하나이다. 가장 큰 DEA 특징은 '**과제 중심적 접근**'과 '**중요한 과제에 추점**'을 맞추어 DMU(Decision Making Units, 의사결정 단위) 성과를 평가한다는 점이다.

주요 특징 및 장점
: - 투입과 산출에 대한 관계설정이 필요 없다.
- 효율적 자원 배분이 가능하다.
- 비효율적인 개선 가능성을 도출할 수 있다.
- 벤치마킹 대상을 도출할 수 있다.
:::

:::{.callout-tip icon=falce title="기출"}
100-3-3
:::

::: {#def-SPA}
## SPA
- SPA,Speciality retailer of Private label Apparel 또는 패스트 패션(Fast fashion) 브랜드란 기획부터 생산, 유톨ㅇ까지 한 회사가 직접 맡아서 판매하는 의류 브랜드를 훈히 가리키는 말이다. 이들은 백화점과 같은 고비용 유통업체를 통하지 않고 대형 직매장을 운영하는 경우가 많은데 이런 중간 유통과정 생략을 통해 재고부탐을 덜고 생산원가를 절감시켜 저렴한 가격에 제품을 공급하며 소비자 요국와 트랜드를 빠르게 반영하는 특징이 있다. 즉, 최신 유행, 상대적을 ㅗ저렴한 가격, 빠른 상품 회전이 특징이다.
- 유명한 SPA 브뢘드로는 UNIQLO(일본), H&M(스웨덴), ZARA(스페인), SPAO(한국), Top10(한국), Le shop(한국), GAP(미국), Forever 21(미국), Topshop(영국) 등이 있다.
:::

:::{.callout-tip icon=falce title="기출"}
103-1-5
:::

::: {#def-efficiency}
## 효율성(efficiency)

최소한 자원으로 주어진 목표를 달성하는 것으로, 생산성 측면에서 산출(output)이 목표라면 최소한 투입(input)으로 산츨을 빨리 이루어내는 것을 효율적이라 한다.
:::

::: {#def-effectiveness}
## 효과성(effectiveness)

목표에 직접 영향을 미치는 핵심적인 부분을 잘 해내는 것으로, 생산성 측면에서 산출(output)이 목표라면 투입(input)에 상관없이 산출을 이루어내면 그것을 효과적이라 한다.
:::

효과성(Effectiveness)|효율성(Efficiency)
목표 달성 | 생산성, 경제성
올바른 일을 하는 것 | 일을 올바르게 하는 것
do the right things | do the things right
방향 | 방법
목표 달성 정도 | 투입 대비 산출

투입 -> 변환 -> 산출 과정에서 투입 대비 산출에 관한 것이 효율성이고, 산촐에 대한 목표 달성 정도를 효과성이라 한다. 즉 효율성은 자원 활용도에 관한 것이고 효과성은 목표 달성도 내지 결과에 대한 만족도를 나타낸다.

::: {#def-lca}

## LCA

LCA(Life Cycle Assessment, 환경전과정평가)는 제품 및 서비스의 원료 채취부터 제조, 유통, 사용 및 폐기에 이르기까지 전과정에 걸친 환경 영향을 정량적으로 분석・평가하는 방법이다.

:::


::: {#def-iot}

## IoT(Internet of Things)

:::{.callout-tip title="기출" icon=false}
106-1-1
:::

**IoT (Internet of Things, 사물인터넷)**는 물리적 장치와 객체들이 인터넷을 통해 서로 연결되어 데이터를 주고받으며 상호작용하는 기술을 의미한다. IoT는 다양한 기기들이 인터넷에 연결되어, 이를 통해 실시간으로 정보를 수집하고 전달하며, 자동화된 방식으로 의사결정을 할 수 있게 한다.

예를 들어, 스마트폰, 스마트홈 장치(조명, 온도조절기, 보안 카메라 등), 웨어러블 기기(스마트워치, 피트니스 트래커 등), 자동차, 심지어 농업 장비까지 다양한 사물들이 IoT 기술을 활용하고 있다. 이 기술은 일상 생활에서 편리함을 높이고, 산업 분야에서 효율성을 증대시킬 수 있다.

IoT 주요 특징
: - 연결성: 다양한 장치들을 인터넷이나 다른 네트워크를 통해 연결되어 상호작용한다.
- 데이터 수집 및 처리: 기기에서 데이터를 수집하고 이를 실시간으로 분석하고 활용한다.
- 자동화 및 제어: IoT 기기들은 설정된 규칙에 따라 자동으로 동작하거나 원격제어할 수 있다.
- 효율성: IoT 기술을 통해 데이터 기반 의사결정이 가능해져 더 효율적인 운영이 가능하다.

예시
: - 스마트홈: 스마트폰을 통해 집의 온도를 조절하거나, 자동으로 불을 켜고 끌 수 있는 시스템
- 스마트 시티: 교통 신호를 자동으로 조정하거나, 공공시설의 에너지 사용을 모니터링하여 효율성을 높이는 시스템
- 헬스케어: 웨어러블 기기를 통해 실시간으로 건강 데이터를 모니터링하고, 이를 기반으로 의료 전문가와 소통

:::

## DNC(Direct Numerical Control)

:::{.callout-tip title="기출" icon=false}
106-1-9
:::

DNC는 NC(수치제어, Numeric Control) 기술이 발전한 형태이다. NC 기술은 공작기계에 적용해서 기계가공을 자동으로행하는 것으로 수치제어가공은 NC공작기계가 중심이 된다. NC공작기계는 정보처리 정도에 따르 다음과 같이 분류할 수 있다.

- 일반 NC공작기계(Conventional NC Machine)
- 머시닝 센터(Machine Ccenter)
- 컴퓨터 수치제어(CNC, Computer Numerical Control)
- 직접 수치제어(DNC, Direct Numerical Control)

DNC기계군은 여러 대 NC 기계를 컴퓨터에 연결하여 외부 기억장치에 저장된 NC용 가공지령정보를 필요에 따라 컴퓨터를 통해 전달받아 공작기계를 움직여 작업을 수행한다.

CNC는 각 기계가 독립적인 프로그램을 가지고 있어 개별적으로 작동한다. 즉 한 번에 작업 하나만을 처리할 수 있다. 이에 반해 DNC는 여러 기계가 네트워크로 연결되어 중앙 서버로부터 명령을 받아 작업을 수행한다. 이로 인해 DNC에서는 한 번에 여러 작업을 동시에 진행할 수 있어 생산성이 향상된다. 또한 DNC는 중앙 서버에서 데이터를 관리하기 때문에 프로그램 업데이트나 변경 사항이 있을 경우 개별 기계 프로그램을 수젇하지 않고 서버에서만 수정하면 되므로 관리가 용이하다는 장점이 있다.

## CRP(Continuous Replenishment Progrma)

:::{.callout-tip title="기출" icon=false}
106-1-10
:::

재고를 자동으로 보충하는 관리방식으로 제조업체와 유통업체 간 각종 제품에 대한 주문 정보를 상호 공유하여 재고를 자동으로 보충, 관리하는 프로그램이다.

## VNI(Ventor Managed Inventory)

:::{.callout-tip title="기출" icon=false}
106-1-11
:::

VMI는 고객기업 재고 및 주문관리를 고객이 작접하지않고 공급자가 책임지는 재고관리 및 조달시스템이다. VMI 방식이 지향하는 목표는 모기업 재고를 최소화하고 납품업체 재고를 모기업에 두고 운영하는 판매 및 재고관리 방법 일환이다.

## 제품가용성(Product Availability)

:::{.callout-tip title="기출" icon=false}
106-1-12
:::

생산된 제품, 즉 재고가 없는 상태에서 고객 주문이 들어오면 재고고갈(stock-out)이 발생한다. 제품가용성은 현재 이용 가능한 재고로부터 고객 주문을 충족시켜 주는 기업 능력을 반영한 지표이다.

1. 제품 충족률(Product Fill Rate): 재고로 있는 제품으로부터 만족되는 제품 수요 비율
2. 주문 충족률(Order Fill Rate): 가용 재고로부터충족되는 주문 비율
3. 주기 서비스 수준(Cycle Service Level): 모든 고객 수요가충족된 보충 주기 비율

## 가상현실(virtual Reality)

:::{.callout-tip title="기출" icon=false}
109-1-1
:::

**가상현실(Virtual Reality, VR)**은 컴퓨터로 생성된 가상 환경에 사용자가 몰입할 수 있게 해주는 기술을 의미한다. VR 기술을 통해 사용자는 현실과는 다른 가상의 세계를 체험할 수 있으며, 주로 시각, 청각, 촉각 등을 이용해 몰입감을 높인다.

가상현실의 주요 특징
: - 몰입감: VR은 사용자에게 완전한 몰입감을 제공한다. 헤드셋을 착용하고 가상의 환경 속에 들어가면, 실제처럼 느껴지는 환경을 경험할 수 있다.
- 인터랙티브: VR은 사용자가 환경 내에서 자유롭게 움직이거나 상호작용할 수 있게 해 준다. 이를 통해 실시간으로 반응하고 조작할 수 있는 경험을 제공한다.
- 3D 환경: VR은 가상의 환경을 3D로 구성하여, 현실감 넘치는 공간을 구현한다. 이로 인해 사용자는 이 공간 안에서 이동하거나 물체와 상호작용할 수 있다.

VR을 이용한 응용 분야
: - 게임: VR은 게임 산업에서 가장 많이 활용되는 기술 중 하나입니다. 사용자는 게임 속 캐릭터가 되어, 가상 환경에서 실시간으로 게임을 즐길 수 있다.
- 교육: VR은 가상 교실이나 실험실을 만들어, 학생들이 현실에서는 경험할 수 없는 상황을 안전하게 배울 수 있도록 도와 준다.
- 의료: VR을 이용해 수술을 연습하거나, 치료용으로 사용되기도 한다. 예를 들어, PTSD(외상 후 스트레스 장애) 치료에 가상현실을 이용한 노출 치료가 진행되기도 한다.
- 건축 및 디자인: 건축가들이 VR을 이용하여 설계한 건물이나 공간을 가상으로 미리 보고, 실제 환경에서 어떤 모습일지 체험할 수 있다.
- 관광: VR을 이용한 가상 여행은 물리적으로 이동할 수 없는 장소나 상황을 체험하는 방법으로 활용된다.

사용 장비
: - VR 헤드셋: 가상현실 환경을 보기 위해 사용하는 장치로, 예를 들어 Oculus Rift, HTC Vive, PlayStation VR 등이 있다.
- 컨트롤러: 가상세계와 상호작용하기 위해 사용하는 장치이다. 손 모양을 추적하거나 버튼을 눌러 다양한 활동을 할 수 있다.
- 모션 추적 장치: 사용자의 움직임을 감지하여 가상 환경에 반영하는 센서나 카메라를 사용하기도 한다.

## CSR

:::{.callout-tip title="기출" icon=false}
109-1-7
:::

CSR(Corporate Social Responsibility, 기업의 사회적 책임)은 기업이 생산 및 영업활동을 하면서 환경경영, 윤리경영, 사회공헌과 노동자를 비롯한 지역사회 등 사회 전체에 이익을 동시에 추구하며, 그에 따라 의사 결정 및 활동을 하는 것을 말한다.

기업의 사회적 책임 피라미드(Pyramid of CSR)는 미국 조지아 대학 아치 캐럴교수가 1991년 발표한 내용으로 **경제적 책임**, **법적 책임**, **윤리적 책임**, **자선적 책임**으로 이루어진다.

경제적 책임
: - 기본적인 기업 책임으로 자본가는 자본을 바탕으로 서비스와 제품을 생산한다.

법적 책임
: - 기업은 법대로 생산, 유통, 판매를 한다.

윤리적 책임
: - 기업은 옳고, 공정하고, 정당한 것을 이행한다.

자선적 책임
: - 좋은 기업 시민이 된다. 공동체 자원을 제공한다. 삶의 질을 개선한다.

## FEA

::: {.callout-tip icon=false title="기출"}
109-1-13
:::

**FEA**(Finaancial effect analyst)란 린 6시그마 프로젝트 재무성과를 평가하고 검증하는 전문가로 프로젝트 재무평가 산정 방법을 수립하고 6시그마 재무성과를 검증하는 업무를 수행한다. 즉, 6시그마 프로젝트에 있어 감사와 회계 전문가이다.
