## 용어 {#sec-terms .unnumbered}

:::{.callout-tip}
## 기출

#97-1-9, #97-1-13
:::

::: {#def-투입시간}
## 투입시간(부하시간)
- 조업시간에 회사가 규정하는 법정 휴지시간을 제외하고설비가 실제 가동하도록 정의된 시간
:::

::: {#def-가동시간}
## 가동시간
- 부하시간에서 정지시간을 제외한 시간으로 설비가 제조(작업)활동을 위해 실제 가동한 시간
- 가동시간 = 부하시간 - 정미시간
:::

::: {#def-정미가동시간}
## 정미가동시간
- 설비가 주어진 기능과 성능을 발휘하여 제품 생산에 기여한 시간
- 정미가동시간 = 가동시간 - 순간정지시간 = 완성수량 x 실제 사이클 타입
:::

::: {#def-표준생산공수}
## 표준생산(량) 공수
- 제품 1개를 만들기 위한 표준작업시간과 생산량을 곱하여 계산되는 것으로, 정해진 방법과 작업 속도로 작업했는지를 판단하는 공수
- $\sum(표준작업시간 \times 생산량)$
:::
::: {#def-사이클타임}
## 사이클 타임 (Cycle time)
- 제품이나 부품 1단위가 공정에서 작업을 시작해서 완료되기까지 연속 경과된 사간을 의미하며, 제품이나 부품 등이 가공되는 대상물 관점에서 보는 시간
:::

::: {#def-피치타임}
## 피치 타임 (Pitch time)
- 최종 공정으로부터 완성품이 되어 나오는 시간적 간격, 즉, 1일 생산목표량을 달성하기 위한 제품 단위당 소요 제작 시간
:::

::: {#def-리드타임}
## 리드 타임 ( Lead time)
- 재료 입고에서부터 완성품 출하(납품)에 이르기까지 시간
- 설계/개발 리드 타임, 부품 조달 리드 타임, 생산 리드 타임, 출하 리드 타임

::: {#def-정미시간}
## 정미시간
- 대상작업의 기본적 내용으로 규칙적, 주기적으로 반복되는 작업 부분의 시간으로, 순수하게 작업에만 사용된 시간
:::

::: {#def-여유시간}
## 여유시간
- 대상작업의 필요한 내용으로 불규칙적, 우발적으로 발생하는 시간
:::

::: {#def-표준시간}
## 표준시간
- 적당한(부과된 작업량을 올바르게 수행) 숙련도를 지닌 작업자가 주어진 작업 조건 하에서 보통 작업 속도와 정상적인 피로와 지연을 수반하면서 규정된 질과 양의 작업을 규정된 방법에 따라 1단위 수행하는데 소요되는 시간
:::

::: {#def-부가원가}
## 부가원가
- 원가이나 비용이 아닌 항목으로 기업주 보수, 자기자본 이자, 기업주 소유 토지계산 지대 등이 해당하며 원가계산상으로 원가로 취급, 손익계산상 비용으로 취급하지 않음
:::

:::{#def-중성비용}
## 중성비용
- 손익계산상으로 비용이나 원가로 취급하지 않는 항목으로 기부금, 유가증권평가손실 등과 같이 생산에 직접 관계가 없는 비용
:::




