## TBD {#sec-tbd .unnumbered}

::: {.callout title="기출" icon=false}
97-2-6  
: 생산 공장의 생산정보관리에 있어서 생산정보를 생산계획 정보, 생산통제 정보, 생산성 정보로 구분하였을 때, 각각의 세부적인 정보의 항목과 내용을 설명하시오.
:::

::: {.callout title="기출"}
100-1-4
: 제조(생산) 8대 프로세스

- 개발, 구매, 제조, 물류, 마케팅, 판매, 서비스, 재무/지원
:::

::: {.callout title="기출"}
100-1-12
: 생산의 유연성과 관련된 경쟁능력 변수

- 새로운 시장 상황과 다양한 고객 요구를 충족하기 위해서는 생산 유연성에 대처하는 능력이 필요하다. 이는 혼류생산 등을 통한 제품 유연성 및 수량 유연성이 그 대표적 경재능력 변수로 볼 수 있다.
:::

::: {.callout icon=false title="기출"}
100-1-13
: JIT시스템의 성공전제조건(제조업 중심)

JIT 적용분야로는 자동차, 오토바이 , 기계, 전자 및 저닉제품, 카메라 등으로 반복적 생산공장에서 도입 적용되고 있다.

성공 전제조건
: - 도요타 생상방식 수단: 즉 하위시스템(JIT, 소로트화, 자동화, TQC 및 현장개선)이 제대로 역할 수 행
- 판매력: 연속생산을 할 수 있도록 생산주문을 연속적으로 보내야 한다.
- 협력적 동반관계: 필요할 때 필요한 양을 납품 받기 위해 하청업체는 원청업체 대신에 재고를 보유하고 적기 공급을 위해 많은 비용과 노력이 발생하게 된다. 따라서 하청업체와 동반 성작하기 위해 적절한 관리가 필요하다.
- 생산평준화가 가능한 체제: 생산 평준화를 달성하기 위해서 될 수 있는 대로 로트를 작게 가져가야 한다. 소로토화를 위해서 생산준비 시간을 단축해야 하고 이에 기술력이 최대 관건이 된다. 자동화와 현장 개선을 위해서는 기술력이 필요하다.
- 생산관리 체제 정비: 설비관리, 품질관리, 재고관리, 물류관리 등 

도요타 생상방식 성립조건
   실현조건<br>목적추구수단   |판매력|하청관리력|기술력|평준화생산<br>가능체제|생산관리<br>체제정비
-|-|-|-|-|-|-
JIT|O|O||O|O
자동화|||O||
소로트화||O|O|O|
:::

:::{.callout-tip icon=false title="기출"}
100-4-3
: 생산관리 측면에서 제조리드타임의 기능과 이를 단축하기 위한 공정개선 방법에 대하여 설명하시오.
:::

:::{.callout-tip icon=false title="기출"}
103-2-4
: 원가절감을 위한 경영활동에 대한 다음 각 물음에 답하시오. 

(1) 기업경영에 있어 한계이익을 최대로 확보하는 것이 왜 중요한지 설명하시오. 
(2) 변동비율의 개념을 설명하고 변동비를 낮추는 원가절감방안을 설명하시오. 
(3) 고정비의 개념을 설명하고 고정비를 낮추는 원가절감방안을 설명하시오.
:::

:::{.callout-tip icon=false title="기출"}
103-3-6
: 생산시스템을 경쟁우위의 수단으로 한다는 것은 전략, 설계, 운영의 의사결정이 일관되고 서로 연결되는 것이 필요하다. 전략적 선택(1순위), 설계의사결정(2순위), 운영의사결정(3순위)의 항목을 공정중심생산방식과 제품중심생산방식으로 구분하여 설명하시오.

----

구분|제품중심생산방식|공정중심생산방식
-|-|-
전략적 선택| |
설계의사결정| |
운영의사결정| |
:::

:::{.callout-tip title="기출" icon=false}
106-4-2
: 공급사슬에서 협력이 결여되면 생산비용, 재고비용, 보충리드타임, 수송비용, 선적과 하역비용 등이 증가하고 제품 가용성 수준 및 수익성이 감소한다. 공급사슬에서 협력 결여 발생요인과 협력을 이루어 내기 위한 관리수단에 대하여 설명하시오.

----

:::

:::{.callout-tip title="기출" icon=false}
106-4-6
: 시간은 비용, 생산성, 품질, 혁신에 버금가는 중요한 전략수단이다. 기업의 경쟁력 제고를 위한 시간단축 경영을 하고자 할 때 고려되어야 할 4가지 사항에 대하여 설명하시오.

----

:::

:::{.callout-tip title="기출" icon=false}
109-1-12
: 생산기간의 정의, 구성 및 단축 필요성에 대하여 각각 설명하시오.

----

:::

:::{.callout-tip title="기출" icon=false}
109-2-4
: ZD(Zero Defect) 프로그램의 실패요인에 대하여 설명하시오.

----

**Zero Defect**(무결점 또는 ZD 운동)은 제조 공정에서 결함을 최소화 하거나 제거하는 품질 관리 전략으로 1962년 미국 마틴사에서 미사일 신뢰도 향상과 원가절감 목적으로 전개시킨 품질향상에 대한 종업원 동기부여 프로그램이다. ZD운동은 "작업자 오류가 주류를 이루고 있으며, 작업자 오류는 적절한 동기부여로써 제거될 수 있다."는 가정에서 비롯되었다.

ZD 프로그램 실패 이유
: - 비용부담: ZD 전략을 실행하려면 상당한 비용이 필요하다. 품질 검사를 강화하고 불량품을 수정 또는 폐기하며, 새로운 프로세스를 도입하는데 드는 비용 등 기업에게는 부담이 될 수 있다.
- 복잡성: ZD를 달성하기 위해서는 복잡하고 많은 시간이 소요된다. 이는 기업 생산성 저하로 이어질 수 있다.
- 인간 요소: 인간 실수나 부주의는 ZD 달성에 있어 장애물 중 하나가 된다. 아무리 좋은 시스템과 프로세스가 있어도 사람 실수는 불가피하다.
- 기술적 한계: 현재 기술로 완벽하게 결함이 없는 제품을 만드는 것이 불가능할 수도 있다.
- 시장 경쟁력: 제품 품질이 중요하지만, 가격, 디자인, 브랜드 이미지 등도 시장에서 경쟁력을 갖추는데 중요한 요소이다. 

이러한 이유로 ZD 프로그램은 항상 성공하지 않을 수 있다.
:::

:::{.callout-tip title="기출" icon=false}
109-3-6
: 기업경쟁력의 원천인 제안제도의 성공요소를 설명하시오.

----

제안제도는 기업 경쟁력에 있어 중요한 원천 중 하나이다. 성공적인 제안제도를 운영하려면 다음과 같은 요소가 필요하다.

1. 참여 분위기 조성
: - 직원들이 자유롭게 아이디어를 제시하고 참여할 수 있는 분위기 조성, 상사의 적극적인 지지와 참여가 필수적

2. 보상체계 확립
: - 직원 제안을 인정하고 그에 따른 합리적인 보상을 젲공하는 체계 마련, 보상은 금전적인 것뿐만 아니라 인사평가 반영, 포상휴가 등도 포함

3. 체계적인 프로세스 구축
: - 제안이 들어오면 그것을 검토하고 실행에 옮기는 프로세스가 체계적이고 구체적으로 구축, 이 과정에서 투명성과 공정성 필수

4. 교육과 훈련
: - 직원에게 제안제도 이용 방법과 제안서 작성법 등에 대한 교육과 훈련 제공, 이를 통해 제안 질 향상

5. 지속적인 개선
: - 제안제도가 성공적으로 운영되더라도 거기서 만족하지 않고 지속적으로 개선 발전
:::
