project:
  type: book
  output-dir: docs

book:
  title: "공장관리기술사"
  author: "yeonkyu.park@gmail.com"
  date: last-modified
  date-format: iso
  repo-url: https://github.com/yeonkyupark/PEPC 
  repo-branch: main
  repo-actions: [edit]
  sidebar: 
    collapse-level: 2
    tools:
      - icon: global
        href: https://yeonkyupark.github.io/
      - icon: instagram
        href: https://www.instagram.com/yeonkyu.park/
  chapters:
    - index.qmd
    # - part: 1. 생산전략.qmd
    - part: "1. 생산전략"
      chapters:
        - 1-1.경쟁우위 생산전략.qmd
        - 1-2.생산구조와 방식(Layout).qmd
        - 1-3.구매와 외주전략.qmd
        - 1-4.인력과 직무설계.qmd
        - 1-5.사업환경분석.qmd
      
    # - part: 2. 생산운영 및 물류관리.qmd
    - part: "2. 생산운영 및 물류관리"
      chapters: 
        - 2-1.수요예측과 일정계획.qmd
        - 2-2.프로세스 진도관리.qmd
        - 2-3.공급망 관리(SCM).qmd
        - 2-4.물류관리(자재 및 재고관리).qmd
        
    # - part: 3. 공정관리.qmd
    - part: "3. 공정관리"
      chapters: 
        - 3-1.생산계획수립.qmd
        - 3-2.공정설계.qmd
        - 3-3.작업계획수립.qmd
        - 3-4.표준작업관리.qmd
        - 3-5.설비보전관리.qmd
        - 3-6.공정개선.qmd
        
    # - part: 4. 설비관리.qmd
    - part: "4. 설비관리"
      chapters: 
        - 4-1.설비계획 및 관리.qmd
        - 4-2.자재취급 및 운반관리.qmd
        - 4-3.환경관리 및 안전관리.qmd
        - 4-4.시설 및 유틸리티관리.qmd
        - 4-5.공장자동화 기술.qmd
        
    # - part: 5. 작업 및 생산성과 측정과 개선.qmd
    - part: "5. 작업 및 생산성과 측정과 개선"
      chapters: 
        - 5-1.작업방법 및 시간 연구.qmd
        - 5-2.프로세스 분석과 개선.qmd
        - 5-3.생산성관리.qmd
        - 5-4.품질관리.qmd
        
    # - part: 6. 원가관리 및 경제성 공학.qmd
    - part: "6. 원가관리 및 경제성 공학"
      chapters: 
        - 6-1.사업성분석.qmd
        - 6-2.원가관리.qmd
        - 6-3.가치공학.qmd
        - 6-4.경영과학(OR).qmd
        
    # - part: 7. 생산지원기술 및 기타.qmd
    - part: "7. 생산지원기술 및 기타"
      chapters: 
        - 7-1.정보화활용기술(스마트팩토리 등).qmd
        - 7-2.제품개발기술.qmd
        - 7-3.서비스운영관리.qmd
        - 7-4.생산혁신기술.qmd
        - 7-5.공장관리에 관한 신기술 및 경향에 관한 사항.qmd
        
    # - part: 8. 참고 자료.qmd
    - part: "8. 참고 자료"
      chapters:
        - 8-2.용어.qmd
        - 8-1.ISO.qmd
        - 8-3.TBD.qmd

bibliography: references.bib 

number-sections: false

format:
  html:
    toc: true
    toc-depth: 4
    toc-title: 목차
    theme: 
      - sandstone
      - custom.scss
    mermaid:
      theme: neutral

# freeze: auto
crossref:
  fig-title: 그림
  tbl-title: 표
  exm-title: 예제
  title-delim: ":"
